## Lab 10 : R y Python


### @autor: Roberto Mendoza

In [61]:
# import libraries 

import pandas as pd 
import numpy as np
import re 
from tqdm import tqdm  # controlar el tiempo en un loop
import os


# linear model library

import statsmodels.api as sm  # linear regression utiliza todas las columnas de base de datos 
import statsmodels.formula.api as smf  # linear regression usa uan formula
from sklearn import datasets, linear_model # models 
from sklearn.metrics import mean_squared_error, r2_score
import warnings
warnings.filterwarnings('ignore') # eliminar warning messages 


# Export latex table 

from pystout import pystout

user = os.getlogin()   # Username
os.chdir(f"C:/Users/{user}/Documents/GitHub/1ECO35_2022_2/Lab10") # Set directorio

#### Statamodels documentation

https://www.statsmodels.org/stable/index.html

#### Pandas documentation

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.io.formats.style.Styler.to_latex.html

## 1.0 Summary estatistics table

In [62]:
# laod dataset

repdata = pd.read_stata(r"../data/dataverse_files/mss_repdata.dta",
                           convert_categoricals=False)

# convert_categoricals=False: No se lee las etiquetas de valor 

repdata

,ccode,year,country_name,country_code,GPCP,GPCP_l,GPCP_l2,GPCP_g,GPCP_g_l,GPCP_g_fl,...,muni,state,author,stconst,fh_civ,fh_pol,S,W,WoverS,soc
0,540.0,1981-01-01,Angola,AGO,839.215759,911.847290,1021.776855,-0.079653,-0.107587,0.155680,...,0.0,1.0,NaN,NaN,0.000000,0.000000,1.0,0.5,0.500712,1.0
1,540.0,1982-01-01,Angola,AGO,969.864563,839.215759,911.847290,0.155680,-0.079653,-0.034482,...,0.0,1.0,NaN,NaN,0.000000,0.000000,1.0,0.5,0.500712,1.0
2,540.0,1983-01-01,Angola,AGO,936.421631,969.864563,839.215759,-0.034482,0.155680,0.059925,...,0.0,1.0,NaN,NaN,0.000000,0.000000,1.0,0.5,0.500712,1.0
3,540.0,1984-01-01,Angola,AGO,992.536255,936.421631,969.864563,0.059925,-0.034482,-0.018277,...,0.0,1.0,NaN,NaN,0.000000,0.000000,1.0,0.5,0.500712,1.0
4,540.0,1985-01-01,Angola,AGO,974.396118,992.536255,936.421631,-0.018277,0.059925,0.216019,...,0.0,1.0,NaN,NaN,0.000000,0.000000,1.0,0.5,0.500712,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
738,552.0,1995-01-01,Zimbabwe,ZWE,493.448456,465.000092,680.722412,0.061179,-0.316902,0.513642,...,NaN,0.0,NaN,NaN,0.333333,0.333333,1.0,0.5,0.500712,0.0
739,552.0,1996-01-01,Zimbabwe,ZWE,746.904236,493.448456,465.000092,0.513642,0.061179,0.044380,...,NaN,0.0,NaN,NaN,0.333333,0.333333,1.0,0.5,0.500712,0.0
740,552.0,1997-01-01,Zimbabwe,ZWE,780.051941,746.904236,493.448456,0.044380,0.513642,-0.181482,...,NaN,0.0,NaN,NaN,0.333333,0.333333,1.0,0.5,0.500712,0.0
741,552.0,1998-01-01,Zimbabwe,ZWE,638.486389,780.051941,746.904236,-0.181482,0.044380,0.094420,...,NaN,0.0,NaN,NaN,0.333333,0.333333,1.0,0.5,0.500712,0.0
742,552.0,1999-01-01,Zimbabwe,ZWE,698.772217,638.486389,780.051941,0.094420,-0.181482,0.428359,...,NaN,0.0,NaN,NaN,0.333333,0.166667,1.0,0.5,0.500712,0.0

In [63]:
# summmary statistics

repdata.describe()

# Tipo de variables

repdata.info()

repdata.dtypes

<class 'pandas.core.frame.DataFrame'>
Int64Index: 743 entries, 0 to 742
Columns: 200 entries, ccode to soc
dtypes: datetime64[ns](1), float32(104), float64(78), int32(9), int8(5), object(3)
memory usage: 813.4+ KB

ccode                  float64
year            datetime64[ns]
country_name            object
country_code            object
GPCP                   float32
                     ...
fh_pol                 float64
S                      float32
W                      float32
WoverS                 float32
soc                    float32
Length: 200, dtype: object

In [64]:
# Extraer year
# con .month se puede extraer el mes 
# con .day se puede extraer el día 

repdata['time_year'] = pd.DatetimeIndex(repdata['year']).year - 1978
repdata['time_year']

0       3
1       4
2       5
3       6
4       7
       ..
738    17
739    18
740    19
741    20
742    21
Name: time_year, Length: 743, dtype: int64

In [65]:
dummys = pd.get_dummies(repdata["ccode"].astype(int), prefix = "ccode", dummy_na=False)
dummys.columns

# se convierte a entero repdata["ccode"].astype(int)

# ccode: código por país 

# dummy_na=False 

# capturar varibbles omitidas invariantes de cada país

Index(['ccode_404', 'ccode_420', 'ccode_432', 'ccode_433', 'ccode_434',
       'ccode_435', 'ccode_436', 'ccode_437', 'ccode_438', 'ccode_439',
       'ccode_450', 'ccode_451', 'ccode_452', 'ccode_461', 'ccode_471',
       'ccode_475', 'ccode_481', 'ccode_482', 'ccode_483', 'ccode_484',
       'ccode_490', 'ccode_500', 'ccode_501', 'ccode_510', 'ccode_516',
       'ccode_517', 'ccode_520', 'ccode_522', 'ccode_530', 'ccode_540',
       'ccode_541', 'ccode_551', 'ccode_552', 'ccode_553', 'ccode_560',
       'ccode_565', 'ccode_570', 'ccode_571', 'ccode_572', 'ccode_580',
       'ccode_625'],
      dtype='object')

In [66]:
dummys

,ccode_404,ccode_420,ccode_432,ccode_433,ccode_434,ccode_435,ccode_436,ccode_437,ccode_438,ccode_439,...,ccode_551,ccode_552,ccode_553,ccode_560,ccode_565,ccode_570,ccode_571,ccode_572,ccode_580,ccode_625
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
738,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
739,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
740,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
741,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
742,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0

In [67]:
len(dummys.columns)

41

##### Reference get_dummies

https://pandas.pydata.org/docs/reference/api/pandas.get_dummies.html

In [68]:
repdata = pd.concat([ repdata , dummys], axis = 1 )

# concantenar ambas bases de datos de manera horizontal (axis = 1)

In [69]:
repdata

,ccode,year,country_name,country_code,GPCP,GPCP_l,GPCP_l2,GPCP_g,GPCP_g_l,GPCP_g_fl,...,ccode_551,ccode_552,ccode_553,ccode_560,ccode_565,ccode_570,ccode_571,ccode_572,ccode_580,ccode_625
0,540.0,1981-01-01,Angola,AGO,839.215759,911.847290,1021.776855,-0.079653,-0.107587,0.155680,...,0,0,0,0,0,0,0,0,0,0
1,540.0,1982-01-01,Angola,AGO,969.864563,839.215759,911.847290,0.155680,-0.079653,-0.034482,...,0,0,0,0,0,0,0,0,0,0
2,540.0,1983-01-01,Angola,AGO,936.421631,969.864563,839.215759,-0.034482,0.155680,0.059925,...,0,0,0,0,0,0,0,0,0,0
3,540.0,1984-01-01,Angola,AGO,992.536255,936.421631,969.864563,0.059925,-0.034482,-0.018277,...,0,0,0,0,0,0,0,0,0,0
4,540.0,1985-01-01,Angola,AGO,974.396118,992.536255,936.421631,-0.018277,0.059925,0.216019,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
738,552.0,1995-01-01,Zimbabwe,ZWE,493.448456,465.000092,680.722412,0.061179,-0.316902,0.513642,...,0,1,0,0,0,0,0,0,0,0
739,552.0,1996-01-01,Zimbabwe,ZWE,746.904236,493.448456,465.000092,0.513642,0.061179,0.044380,...,0,1,0,0,0,0,0,0,0,0
740,552.0,1997-01-01,Zimbabwe,ZWE,780.051941,746.904236,493.448456,0.044380,0.513642,-0.181482,...,0,1,0,0,0,0,0,0,0,0
741,552.0,1998-01-01,Zimbabwe,ZWE,638.486389,780.051941,746.904236,-0.181482,0.044380,0.094420,...,0,1,0,0,0,0,0,0,0,0
742,552.0,1999-01-01,Zimbabwe,ZWE,698.772217,638.486389,780.051941,0.094420,-0.181482,0.428359,...,0,1,0,0,0,0,0,0,0,0

In [70]:
# Creación del trend_country effects : multiplicación de las dummy por país y la variable temporal 
# capturar variables omitidas variantes en el tiempo por cada país. 

i = 0

while i < 41:  # 41 por el tema de indexing pues en python la posición inicial es cero. 
    var = dummys.columns[i]+"_"+"time"  # creamos el nombre de cada variable
    repdata[var]  = repdata[dummys.columns[i]]*repdata["time_year"] 
    
    # multiplicacón de variables: dummy país * variable temporal

    i = i + 1

In [71]:
# observamos para país y la variable temporarl. 

repdata[['ccode','time_year']].iloc[0:40,:]

    ccode  time_year
0   540.0          3
1   540.0          4
2   540.0          5
3   540.0          6
4   540.0          7
5   540.0          8
6   540.0          9
7   540.0         10
8   540.0         11
9   540.0         12
10  540.0         13
11  540.0         14
12  540.0         15
13  540.0         16
14  540.0         17
15  540.0         18
16  540.0         19
17  540.0         20
18  540.0         21
19  434.0          3
20  434.0          4
21  434.0          5
22  434.0          6
23  434.0          7
24  434.0          8
25  434.0          9
26  434.0         10
27  434.0         11
28  434.0         12
29  434.0         13
30  434.0         14
31  434.0         15
32  434.0         16
33  434.0         17
34  434.0         18
35  434.0         19
36  434.0         20
37  434.0         21
38  571.0          3
39  571.0          4

In [72]:
# Seleccionamos las variables para las estadísticas descriptivas

table1 = repdata.loc[:,["any_prio", "any_prio_on", "any_prio_off","war_prio", "war_prio_on", "war_prio_off",
                        "war_col", "war_inc", "war","GPCP", "GPCP_g", "GPCP_g_l","gdp_g", "gdp_g_l",
        "y_0", "polity2l", "polity2l_6", "ethfrac", "relfrac", "Oil", "lmtnest", "lpopl1", "tot_100_g"]]

table1

,any_prio,any_prio_on,any_prio_off,war_prio,war_prio_on,war_prio_off,war_col,war_inc,war,GPCP,...,gdp_g_l,y_0,polity2l,polity2l_6,ethfrac,relfrac,Oil,lmtnest,lpopl1,tot_100_g
0,1.0,NaN,0.0,1.0,NaN,0.0,1.0,1.0,1.0,839.215759,...,0.019637,0.662,-7.0,0.0,0.783282,0.6122,1.0,2.370244,8.933400,NaN
1,1.0,NaN,0.0,1.0,NaN,0.0,1.0,1.0,1.0,969.864563,...,-0.037037,0.662,-7.0,0.0,0.783282,0.6122,1.0,2.370244,8.959697,NaN
2,1.0,NaN,0.0,1.0,NaN,0.0,1.0,1.0,1.0,936.421631,...,0.044615,0.662,-7.0,0.0,0.783282,0.6122,1.0,2.370244,8.985946,NaN
3,1.0,NaN,0.0,1.0,NaN,0.0,1.0,1.0,1.0,992.536255,...,-0.008837,0.662,-7.0,0.0,0.783282,0.6122,1.0,2.370244,9.012134,NaN
4,1.0,NaN,0.0,1.0,NaN,0.0,1.0,1.0,1.0,974.396118,...,0.026746,0.662,-7.0,0.0,0.783282,0.6122,1.0,2.370244,9.035987,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
738,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,0.0,493.448456,...,0.030296,1.190,-6.0,0.0,0.543950,0.5098,0.0,1.360977,9.285019,-0.006359
739,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,0.0,746.904236,...,-0.018779,1.190,-6.0,0.0,0.543950,0.5098,0.0,1.360977,9.306650,0.001000
740,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,0.0,780.051941,...,0.078490,1.190,-6.0,0.0,0.543950,0.5098,0.0,1.360977,9.327418,0.095405
741,1.0,1.0,NaN,1.0,1.0,NaN,0.0,0.0,0.0,638.486389,...,0.008137,1.190,-6.0,0.0,0.543950,0.5098,0.0,1.360977,9.347324,-0.006019
742,1.0,NaN,0.0,1.0,NaN,0.0,0.0,0.0,0.0,698.772217,...,0.017494,1.190,-6.0,0.0,0.543950,0.5098,0.0,1.360977,9.366368,-0.079282

In [73]:
# selccionamos los estadísticos de interés: media, error estándar y cantidad de observaciones

summary_table = table1.describe().loc[["mean","std","count"]]
summary_table

,any_prio,any_prio_on,any_prio_off,war_prio,war_prio_on,war_prio_off,war_col,war_inc,war,GPCP,...,gdp_g_l,y_0,polity2l,polity2l_6,ethfrac,relfrac,Oil,lmtnest,lpopl1,tot_100_g
mean,0.267833,0.068468,0.143617,0.166891,0.036800,0.144068,0.169583,0.220994,0.244953,1001.638367,...,-0.005552,1.163855,-3.608345,0.146703,0.654632,0.486754,0.118439,1.578309,8.749662,-0.006802
std,0.443128,0.252776,0.351638,0.373129,0.188421,0.352656,0.375518,0.415203,0.430350,501.701569,...,0.072391,0.900927,5.554322,0.354049,0.237388,0.185715,0.323345,1.433366,1.206843,0.155209
count,743.000000,555.000000,188.000000,743.000000,625.000000,118.000000,743.000000,724.000000,743.000000,743.000000,...,743.000000,743.000000,743.000000,743.000000,743.000000,743.000000,743.000000,743.000000,743.000000,661.000000

In [74]:
summary_table = table1.describe().loc[["mean","std","count"]].T
summary_table
# .t permite tranponer el DataFrame

                     mean         std  count
any_prio         0.267833    0.443128  743.0
any_prio_on      0.068468    0.252776  555.0
any_prio_off     0.143617    0.351638  188.0
war_prio         0.166891    0.373129  743.0
war_prio_on      0.036800    0.188421  625.0
war_prio_off     0.144068    0.352656  118.0
war_col          0.169583    0.375518  743.0
war_inc          0.220994    0.415203  724.0
war              0.244953    0.430350  743.0
GPCP          1001.638367  501.701569  743.0
GPCP_g           0.018195    0.209413  743.0
GPCP_g_l         0.011271    0.206667  743.0
gdp_g           -0.004754    0.070698  743.0
gdp_g_l         -0.005552    0.072391  743.0
y_0              1.163855    0.900927  743.0
polity2l        -3.608345    5.554322  743.0
polity2l_6       0.146703    0.354049  743.0
ethfrac          0.654632    0.237388  743.0
relfrac          0.486754    0.185715  743.0
Oil              0.118439    0.323345  743.0
lmtnest          1.578309    1.433366  743.0
lpopl1           8.749662    1.206843  743.0
tot_100_g       -0.006802    0.155209  661.0

In [75]:
table1.columns

Index(['any_prio', 'any_prio_on', 'any_prio_off', 'war_prio', 'war_prio_on',
       'war_prio_off', 'war_col', 'war_inc', 'war', 'GPCP', 'GPCP_g',
       'GPCP_g_l', 'gdp_g', 'gdp_g_l', 'y_0', 'polity2l', 'polity2l_6',
       'ethfrac', 'relfrac', 'Oil', 'lmtnest', 'lpopl1', 'tot_100_g'],
      dtype='object')

In [76]:
table1.columns

new_names = ["Civil conflict with ≥25 deaths: (PRIO/Uppsala)","Onset","Offset",
"Civil conflict with ≥1,000 deaths:PRIO/Uppsala","Onset","Offset","Collier and Hoeffler (2002)",  
"Doyle and Sambanis (2000)","Fearon and Laitin (2003)",
"Annual rainfall (mm), GPCP measure",
"Annual growth in rainfall, time t",
"Annual growth in rainfall, time t-1",
"Annual economic growth rate, time t",
"Annual economic growth rate, time t-1",
"Log(GDP per capita), 1979",
"Democracy level (Polity IV score, -10 to 10), time t-1",
"Democracy indicator (Polity IV score > 15),time t-1",
"Ethnolinguistic fractionalization (source:Atlas Marodov Mira)",
"Religious fractionalization (source: CIAFactbook)",
"Oil-exporting country (source: WDI)",
"Log(mountainous) (source: Fearon and Laitin 2003)",
"Log(national population), time t-1 (source: WDI)",
"Growth in terms of trade, time t (source:WDI)"]

# unión de listas bajo la estructura diccionario

dict( zip( table1.columns, new_names) )

{'any_prio': 'Civil conflict with ≥25 deaths: (PRIO/Uppsala)',
 'any_prio_on': 'Onset',
 'any_prio_off': 'Offset',
 'war_prio': 'Civil conflict with ≥1,000 deaths:PRIO/Uppsala',
 'war_prio_on': 'Onset',
 'war_prio_off': 'Offset',
 'war_col': 'Collier and Hoeffler (2002)',
 'war_inc': 'Doyle and Sambanis (2000)',
 'war': 'Fearon and Laitin (2003)',
 'GPCP': 'Annual rainfall (mm), GPCP measure',
 'GPCP_g': 'Annual growth in rainfall, time t',
 'GPCP_g_l': 'Annual growth in rainfall, time t-1',
 'gdp_g': 'Annual economic growth rate, time t',
 'gdp_g_l': 'Annual economic growth rate, time t-1',
 'y_0': 'Log(GDP per capita), 1979',
 'polity2l': 'Democracy level (Polity IV score, -10 to 10), time t-1',
 'polity2l_6': 'Democracy indicator (Polity IV score > 15),time t-1',
 'ethfrac': 'Ethnolinguistic fractionalization (source:Atlas Marodov Mira)',
 'relfrac': 'Religious fractionalization (source: CIAFactbook)',
 'Oil': 'Oil-exporting country (source: WDI)',
 'lmtnest': 'Log(mountainous) (source: Fearon and Laitin 2003)',
 'lpopl1': 'Log(national population), time t-1 (source: WDI)',
 'tot_100_g': 'Growth in terms of trade, time t (source:WDI)'}

In [77]:
# Customize summary table 

index_nuevos_nombres = dict( zip( table1.columns, new_names) )

columns_nuevos_nombres = {
    "mean": "Mean",
    "std": "Standard Deviation",
    "count": "Observations",
}

# Rename rows (indexes) and columns
summary_table.rename(index=index_nuevos_nombres, columns=columns_nuevos_nombres, inplace=True)

In [78]:
summary_table

,Mean,Standard Deviation,Observations
Civil conflict with ≥25 deaths: (PRIO/Uppsala),0.267833,0.443128,743.0
Onset,0.068468,0.252776,555.0
Offset,0.143617,0.351638,188.0
"Civil conflict with ≥1,000 deaths:PRIO/Uppsala",0.166891,0.373129,743.0
Onset,0.036800,0.188421,625.0
Offset,0.144068,0.352656,118.0
Collier and Hoeffler (2002),0.169583,0.375518,743.0
Doyle and Sambanis (2000),0.220994,0.415203,724.0
Fearon and Laitin (2003),0.244953,0.430350,743.0
"Annual rainfall (mm), GPCP measure",1001.638367,501.701569,743.0
"Annual growth in rainfall, time t",0.018195,0.209413,743.0
"Annual growth in rainfall, time t-1",0.011271,0.206667,743.0
"Annual economic growth rate, time t",-0.004754,0.070698,743.0
"Annual economic growth rate, time t-1",-0.005552,0.072391,743.0
"Log(GDP per capita), 1979",1.163855,0.900927,743.0
"Democracy level (Polity IV score, -10 to 10), time t-1",-3.608345,5.554322,743.0
"Democracy indicator (Polity IV score > 15),time t-1",0.146703,0.354049,743.0
Ethnolinguistic fractionalization (source:Atlas Marodov Mira),0.654632,0.237388,743.0
Religious fractionalization (source: CIAFactbook),0.486754,0.185715,743.0
Oil-exporting country (source: WDI),0.118439,0.323345,743.0
Log(mountainous) (source: Fearon and Laitin 2003),1.578309,1.433366,743.0
"Log(national population), time t-1 (source: WDI)",8.749662,1.206843,743.0
"Growth in terms of trade, time t (source:WDI)",-0.006802,0.155209,661.0

In [79]:
# Export the DataFrame to LaTeX
# \ permite esccribir código extenso en lineas diferentes

summary_table.style.format(subset="Mean", precision=2).format(subset="Standard Deviation", precision=2)\
.format(subset="Observations", precision=0)\
.to_latex(
    "summary2.tex",
caption="Descriptive Statistics",
    column_format = "lccc"   # l: left, c:center , 
)

In [80]:
#Columns format

summary_table.style.format(subset="Mean", precision=2).format(subset="Standard Deviation", precision=2).format(subset="Observations", precision=0)

## 2.0 First stage

#### Linear models libraries

https://www.statsmodels.org/stable/index.html

#### Standar error jupyter notebook

https://github.com/vgreg/python-se/blob/master/Standard%20errors%20in%20Python.ipynb

In [81]:

y = repdata['gdp_g']

# add constant

X = sm.add_constant(repdata.loc[:,["GPCP_g", "GPCP_g_l"]])

# sm function

ols_model = sm.OLS(y, X).fit()

# fit() permite correr la regresión

print(ols_model.summary())

# Robust standar error

ols_model_rb = sm.OLS(y, X).fit(cov_type = "HC1")
print(ols_model_rb.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                  gdp_g   R-squared:                       0.024
Model:                            OLS   Adj. R-squared:                  0.021
Method:                 Least Squares   F-statistic:                     8.912
Date:                Sat, 12 Nov 2022   Prob (F-statistic):           0.000150
Time:                        01:14:54   Log-Likelihood:                 923.53
No. Observations:                 743   AIC:                            -1841.
Df Residuals:                     740   BIC:                            -1827.
Df Model:                           2
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         -0.0061      0.003     -2.375      0.018      -0.011      -0.001
GPCP_g         0.0554      0.013      4.126      0.000       0.029       0.082
GPCP_g_l       0.0341      0.014      2.502      0.013       0.007       0.061
==============================================================================
Omnibus:                      233.849   Durbin-Watson:                   1.912
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             8701.616
Skew:                           0.693   Prob(JB):                         0.00
Kurtosis:                      19.708   Cond. No.                         6.26
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
                            OLS Regression Results
==============================================================================
Dep. Variable:                  gdp_g   R-squared:                       0.024
Model:                            OLS   Adj. R-squared:                  0.021
Method:                 Least Squares   F-statistic:                     8.703
Date:                Sat, 12 Nov 2022   Prob (F-statistic):           0.000184
Time:                        01:14:54   Log-Likelihood:                 923.53
No. Observations:                 743   AIC:                            -1841.
Df Residuals:                     740   BIC:                            -1827.
Df Model:                           2
Covariance Type:                  HC1
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
const         -0.0061      0.003     -2.349      0.019      -0.011      -0.001
GPCP_g         0.0554      0.014      3.909      0.000       0.028       0.083
GPCP_g_l       0.0341      0.012      2.862      0.004       0.011       0.057
==============================================================================
Omnibus:                      233.849   Durbin-Watson:                   1.912
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             8701.616
Skew:                           0.693   Prob(JB):                         0.00
Kurtosis:                      19.708   Cond. No.                         6.26
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC1)

In [82]:
#alternative robust standar error

ols_model_rb0 = sm.OLS(y, X).fit(cov_type = "HC0") # White robust se
ols_model_rb1 = sm.OLS(y, X).fit(cov_type = "HC1") # Huber-White robust se
ols_model_rb2 = sm.OLS(y, X).fit(cov_type = "HC2") # Eicker-Huber-White robust
ols_model_rb3 = sm.OLS(y, X).fit(cov_type = "HC3")

print(ols_model_rb3.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                  gdp_g   R-squared:                       0.024
Model:                            OLS   Adj. R-squared:                  0.021
Method:                 Least Squares   F-statistic:                     8.425
Date:                Sat, 12 Nov 2022   Prob (F-statistic):           0.000241
Time:                        01:14:54   Log-Likelihood:                 923.53
No. Observations:                 743   AIC:                            -1841.
Df Residuals:                     740   BIC:                            -1827.
Df Model:                           2
Covariance Type:                  HC3
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
const         -0.0061      0.003     -2.345      0.019      -0.011      -0.001
GPCP_g         0.0554      0.014      3.826      0.000       0.027       0.084
GPCP_g_l       0.0341      0.012      2.845      0.004       0.011       0.058
==============================================================================
Omnibus:                      233.849   Durbin-Watson:                   1.912
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             8701.616
Skew:                           0.693   Prob(JB):                         0.00
Kurtosis:                      19.708   Cond. No.                         6.26
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC3)

In [83]:
# Acceder a la información de la tabla

ols_model_rb.summary2()

ols_model_rb.summary2().tables[1]

             Coef.  Std.Err.         z     P>|z|    [0.025    0.975]
const    -0.006147  0.002617 -2.348553  0.018847 -0.011276 -0.001017
GPCP_g    0.055430  0.014180  3.908990  0.000093  0.027637  0.083222
GPCP_g_l  0.034058  0.011901  2.861785  0.004213  0.010733  0.057384

In [89]:
dir(sm.OLS(y, X))

# Lista de atributos y métodos

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_check_kwargs',
 '_data_attr',
 '_df_model',
 '_df_resid',
 '_fit_collinear',
 '_fit_ridge',
 '_fit_zeros',
 '_formula_max_endog',
 '_get_init_kwds',
 '_handle_data',
 '_init_keys',
 '_kwargs_allowed',
 '_setup_score_hess',
 '_sqrt_lasso',
 'data',
 'df_model',
 'df_resid',
 'endog',
 'endog_names',
 'exog',
 'exog_names',
 'fit',
 'fit_regularized',
 'from_formula',
 'get_distribution',
 'hessian',
 'hessian_factor',
 'information',
 'initialize',
 'k_constant',
 'loglike',
 'nobs',
 'predict',
 'rank',
 'score',
 'weights',
 'wendog',
 'wexog',
 'whiten']

In [91]:
# Y estimados a partir del método predict 

sm.OLS(y, X).fit().predict()

array([-1.42260619e-02, -2.30289275e-04, -2.75588850e-03, -3.99951658e-03,
       -5.11886194e-03,  5.20467567e-03, -4.52656919e-03, -1.47307556e-03,
       -7.57119488e-03, -7.20355307e-03, -1.54943854e-02, -2.62602686e-02,
        1.09830081e-02,  1.89986099e-03, -1.11163789e-02, -1.02624190e-02,
       -1.20478876e-02, -1.21560929e-02,  8.62539879e-03, -1.06533385e-02,
       -5.08819333e-03, -1.09503776e-02, -2.79938414e-03, -8.80790188e-04,
       -5.48086194e-03, -1.19531737e-02, -6.60572684e-05,  6.06420773e-03,
       -1.40420956e-02,  8.71916478e-03, -3.72654491e-04, -1.26444387e-02,
        2.99566205e-03, -8.61545720e-03, -1.12166543e-02, -7.62369658e-03,
       -1.53913776e-04, -3.99256394e-03,  2.67528245e-03, -2.05404714e-02,
       -1.24874715e-02, -1.54401360e-02, -4.92022890e-03,  5.35682032e-03,
       -1.36477944e-02,  3.22587198e-02,  1.40012843e-02, -2.94265140e-02,
        2.63542414e-03, -2.05920036e-02,  1.88237806e-02,  1.47617514e-02,
       -3.84554192e-03,  6.28180087e-03,  2.60850052e-03, -1.69360674e-02,
       -1.87055303e-02, -1.06568119e-02, -7.07741836e-03, -1.36631634e-02,
       -4.14889783e-03,  7.49274206e-03,  1.54346014e-04, -1.08992067e-02,
       -1.72849631e-03,  2.96337488e-04, -1.61745252e-02,  5.86511435e-03,
        5.61166534e-04, -1.23689918e-02,  3.07493121e-03, -7.92265843e-03,
       -1.04894856e-02, -4.60612243e-03, -2.11358517e-03, -9.57423686e-04,
       -6.67517856e-03,  1.22965597e-02, -9.00340678e-03, -1.61108075e-02,
        3.75970514e-03, -4.84776579e-03, -8.65702038e-03,  2.85756615e-03,
       -8.43076781e-04, -1.30507235e-02, -1.30197991e-02, -1.18182142e-02,
       -1.78166372e-02, -8.21062419e-03, -3.35007781e-03, -5.39361637e-03,
       -1.69047244e-03, -1.21443488e-02, -1.29127100e-03, -9.21995510e-03,
       -3.72725102e-03, -1.41182274e-02, -5.69924520e-03,  3.15930321e-03,
       -8.60761702e-03, -1.24192487e-02, -1.19103700e-03, -6.23501950e-03,
       -3.26443945e-04, -5.25661583e-03, -7.96442323e-03, -2.33726718e-03,
       -5.95514755e-03, -7.56094159e-03, -6.03294466e-03, -6.28765586e-03,
       -1.14532270e-02,  9.73960635e-04, -3.75518207e-03, -2.78000498e-03,
       -1.14324183e-02, -1.51849292e-02,  1.95536376e-03, -1.26213163e-03,
       -6.89183247e-03, -1.44501683e-03, -1.92660463e-03, -5.05028616e-03,
       -6.01936021e-03, -1.03095716e-02, -1.04609789e-02, -3.35208639e-03,
       -4.27896960e-03, -6.27522988e-03, -1.08211859e-02, -2.07863448e-03,
        1.11724000e-03, -7.17678580e-03, -1.61120840e-02, -1.49859598e-02,
       -2.18133690e-02,  4.73305972e-03, -3.31287357e-04, -1.44846804e-02,
        1.70404320e-02, -6.85024883e-05, -2.91207516e-02,  5.22624222e-03,
        1.26197785e-02, -1.44954687e-02,  2.17206136e-02,  4.59919030e-03,
       -1.43004965e-02, -1.37885515e-02,  1.57781556e-04,  6.04228433e-03,
        2.54908691e-03, -2.62974788e-04, -1.41033213e-02,  1.29379983e-03,
        5.83535629e-03, -1.36727166e-02, -9.96686833e-03,  2.94288908e-03,
       -5.67846033e-03, -1.06288033e-02, -1.68243736e-02, -5.96941943e-03,
       -2.13908408e-03, -4.83218835e-03, -3.09947388e-03, -8.10425424e-03,
       -1.47228334e-02, -1.98879909e-03,  3.57162958e-03,  1.58809971e-02,
        2.83256349e-03, -1.43275965e-02, -2.54440144e-02, -1.06170217e-03,
       -4.50927106e-04, -9.92856075e-03,  4.23894484e-03,  7.00318523e-03,
       -2.08829275e-02, -2.61989789e-02,  3.61384886e-03, -2.72653059e-06,
       -1.55140989e-02, -2.24908439e-02,  1.76243207e-03,  6.99334902e-04,
       -2.66193317e-03,  1.03773183e-03, -3.20475878e-03, -1.26885541e-02,
       -1.60023507e-02, -4.28380475e-03,  9.80302036e-03, -2.88197478e-03,
       -1.21779479e-02,  1.19679471e-02, -1.85715122e-03, -1.97061607e-02,
       -9.69287403e-03,  5.50345984e-04, -9.24247081e-04, -1.55602563e-02,
        6.14855098e-03,  5.46237698e-03, -1.08603421e-02, -1.10122700e-02,
        8.59563331e-04, -6.00604517e-03, -1.34195019e-02, -1.61597176e-02,
       -5.02169528e-03, -3.03258617e-04, -5.44568922e-03, -5.94753301e-03,
       -5.92645876e-03, -1.28607249e-02, -1.53063874e-03,  6.01934927e-03,
        1.73841910e-03, -3.48655103e-03, -2.26460704e-02, -5.36403460e-03,
        5.02781144e-03,  1.16980119e-02,  3.66527777e-03,  2.73666585e-03,
       -5.97146967e-03, -2.23222043e-02, -1.29729127e-02, -2.12980138e-03,
       -1.44581580e-04,  6.08649575e-03, -1.04935756e-02, -1.12821355e-02,
       -9.16048916e-03, -8.33905363e-03,  5.97198362e-03, -1.31180799e-02,
       -1.51084550e-02, -1.82427247e-02,  1.11281442e-02,  1.17348989e-02,
       -1.01081093e-02, -4.48083013e-04, -7.68420585e-03, -2.72814548e-03,
       -1.12412996e-02,  4.05607628e-03, -1.27260421e-02, -1.10448204e-02,
       -9.22133270e-03, -8.85198257e-04, -4.97330829e-03, -6.61235599e-03,
       -1.57873136e-02,  9.77821165e-03, -1.69046261e-03, -8.81813992e-03,
       -2.20918651e-02, -1.18876084e-02, -9.79877798e-04,  6.31579977e-03,
       -6.20978481e-04, -2.80020849e-03, -1.61184737e-03, -7.62454882e-03,
       -3.80863698e-03, -4.43454224e-03, -1.06833632e-02, -5.70021534e-04,
       -1.08291646e-02, -1.52683884e-02, -1.16055006e-02, -4.70006423e-03,
       -7.59348563e-03,  1.64987809e-03,  9.48953393e-04, -1.72772638e-02,
       -8.01288037e-03, -1.76504781e-03, -2.48948682e-03,  7.08883698e-03,
        6.21468017e-03, -3.45197345e-03, -1.86967163e-02, -3.87914630e-03,
       -4.37023695e-03,  3.53504031e-03, -5.57462483e-03, -9.81104501e-03,
       -5.21660842e-03, -7.04846888e-03, -1.08293373e-02,  3.50532083e-03,
       -1.17256446e-02, -7.05233182e-03, -1.90651509e-02,  6.11873837e-03,
        6.18985841e-03, -9.86131349e-03, -2.97046499e-03, -8.51387871e-03,
       -3.15709320e-03, -1.05905013e-02, -5.90778712e-03, -9.29026958e-03,
       -8.06682967e-03, -2.65500585e-03, -2.95050392e-03, -1.06354450e-02,
       -1.25860144e-02, -7.54259739e-03, -1.36547816e-03, -6.31832384e-04,
        2.17604455e-02, -1.62053681e-02, -1.85701079e-02,  3.22492623e-03,
       -6.09433889e-03, -1.81035172e-02,  1.13908325e-03,  3.14299470e-03,
       -7.49367936e-03, -2.02883697e-02, -1.02622516e-02, -1.01231583e-02,
        3.19215280e-03, -2.90877311e-03, -1.66266233e-02,  3.85899594e-02,
        9.24289601e-03, -3.03992586e-02,  7.02845610e-03, -1.01216456e-02,
       -8.56591473e-03, -5.64962285e-03, -1.61077169e-03,  2.44160439e-03,
        4.98450290e-03,  5.11555436e-03, -1.00016412e-02, -2.40764493e-02,
       -1.95072273e-03, -1.51558233e-02,  8.28862423e-03, -2.39498356e-04,
        1.20522594e-03,  1.29648454e-02, -7.04704587e-03, -1.06173698e-02,
       -1.40591527e-02, -6.83096490e-03, -6.95966986e-03, -2.06141581e-02,
       -9.88652457e-04, -1.72941088e-03, -4.18058625e-03, -1.22889722e-03,
       -4.77693130e-03, -1.40094490e-03, -1.59749333e-02, -1.44254240e-02,
       -1.79317188e-03,  2.17369383e-03, -9.97841430e-03, -5.96893564e-03,
       -1.24030268e-02, -4.35276473e-03, -9.79026645e-03, -7.58482481e-03,
        6.66782731e-03, -1.53035770e-02, -7.87253930e-03, -5.05123922e-03,
       -3.82536065e-03,  2.36648171e-04, -2.62655977e-03, -8.74010860e-03,
       -9.50441417e-03, -5.60700870e-03, -1.47292167e-02, -2.15803513e-02,
        2.56285019e-03, -6.33449743e-03, -1.71304395e-03,  4.88501284e-03,
       -8.08610285e-03, -2.52053645e-02, -3.50986954e-04,  1.97431287e-02,
       -1.77279014e-02, -5.63552649e-03, -1.72948728e-02,  4.13162268e-03,
       -4.04206119e-03, -5.64487408e-03,  3.88492198e-03,  6.03841996e-04,
       -1.90028909e-02,  1.42274439e-02, -8.47351282e-03, -1.76912670e-02,
       -1.66428240e-02, -9.00972802e-03,  4.80028656e-03,  3.38754405e-03,
       -1.32682670e-02,  7.81771200e-03,  1.16055702e-03, -2.07520859e-02,
       -7.04860625e-04,  2.56304768e-03, -1.02503025e-02,  1.64696236e-02,
       -4.20137202e-03, -1.88147846e-02, -1.04943236e-02,  5.58601417e-03,
        7.32730406e-03, -4.17799413e-03, -2.09386424e-02, -2.16374364e-02,
       -2.55225812e-03,  4.62252942e-03, -1.57317509e-03, -1.63375316e-02,
        6.88187592e-03,  1.34603930e-02, -2.66845714e-02, -1.92425191e-02,
       -8.99222964e-03,  1.47404705e-02,  2.95988898e-02,  3.30037844e-03,
       -2.44023279e-02, -1.64400960e-02, -1.43358938e-03,  1.49920075e-02,
       -3.90342143e-03, -7.76771363e-03, -1.34380004e-02,  2.74184333e-03,
        5.72649358e-03, -7.93698922e-03, -2.55644419e-02,  5.90048848e-03,
        1.22136226e-02, -1.84973818e-02, -1.18571420e-02, -1.89135480e-02,
        2.37023225e-03, -6.19049821e-03, -4.85467002e-03,  1.12035206e-02,
        6.25022356e-03, -1.63637582e-02,  4.27647180e-03,  3.27967470e-03,
       -3.28050503e-02,  6.81715510e-02,  3.53874170e-02, -2.98197642e-02,
       -6.97085087e-03,  3.05592054e-02, -1.51452170e-02,  5.60621696e-03,
       -1.71183996e-02, -1.55325247e-02, -1.55299751e-02, -1.83299202e-02,
        5.43315439e-03, -2.67202304e-03, -2.82441747e-02,  2.05633867e-02,
        9.78970771e-03, -2.96380027e-02,  1.26519555e-02,  9.92466648e-03,
       -1.43889179e-02,  3.82287721e-02,  4.38326948e-03, -2.15752652e-02,
       -1.08396475e-02,  1.36547966e-02,  7.57779790e-03, -1.37351113e-02,
       -8.98838485e-03, -1.37833701e-02, -7.34790213e-03,  1.34084157e-03,
       -3.66085784e-03, -1.04711068e-02,  2.91602420e-03,  1.38573675e-03,
       -7.82691417e-03, -4.70527922e-03, -6.40660080e-03, -7.54861668e-03,
       -4.77771702e-04, -2.12573039e-03, -8.72751086e-03, -6.94766452e-03,
       -1.00136272e-02, -1.97340435e-03, -7.30186705e-03,  1.07758275e-02,
       -9.31048881e-03, -1.27204888e-02,  4.27240192e-03, -9.58720241e-03,
       -4.93119629e-03,  9.02311267e-03, -5.87041244e-03, -1.23490522e-02,
       -1.45594832e-02, -1.48609002e-02, -1.09293754e-02, -2.31195649e-03,
       -1.86068297e-03, -4.58681056e-03, -6.93700471e-03, -1.19424851e-02,
       -5.73678666e-03,  1.36365244e-04, -3.60086205e-03, -2.30720684e-02,
       -5.60577973e-03,  6.69740750e-03,  8.61061378e-03,  1.37475850e-03,
        3.59575035e-03, -3.80141723e-03, -2.41603295e-02, -1.42840476e-02,
       -2.83990257e-03,  1.29708417e-03,  5.33015464e-03, -8.77407446e-03,
       -1.12885691e-02, -1.14999933e-02, -7.29725215e-03,  7.16432103e-03,
       -2.26497163e-03, -6.11751062e-03, -1.87745007e-02, -1.23825634e-02,
       -3.60754178e-03,  6.24814446e-03,  1.25826668e-03, -9.73383607e-03,
       -4.27627980e-03, -8.74589634e-03, -6.15994803e-03, -1.26325265e-03,
       -7.16358415e-03, -8.59219726e-03, -1.03829239e-02, -1.40781306e-02,
       -1.73570039e-02, -9.02394459e-03, -1.13768564e-02,  2.75841322e-02,
        3.59983817e-02, -2.79765778e-02,  1.47078470e-04,  1.47155516e-02,
       -3.12949593e-02,  2.55514413e-02,  1.63278639e-02,  5.93074809e-03,
       -3.96442262e-03, -2.76913056e-02,  7.29159954e-03, -1.25984320e-02,
       -1.59024301e-02, -9.34401377e-03,  5.93157286e-03, -5.29849637e-03,
       -9.46718228e-03,  9.35779090e-03, -3.55792979e-03, -2.29901957e-02,
       -1.08833556e-04, -1.45883263e-02,  4.67199113e-03, -5.91106432e-04,
        6.32038366e-03,  1.08719188e-02, -9.71111338e-03, -1.66182666e-02,
       -1.34523272e-02, -5.22376994e-03, -1.49039445e-02, -1.50089028e-02,
       -1.96284407e-02,  1.19765065e-02,  8.34686438e-03, -4.16980028e-03,
        6.90586171e-03, -2.64421829e-03, -2.22460367e-02, -7.53438792e-03,
        1.88984029e-03, -1.11659316e-03, -2.42305572e-03, -3.88998012e-03,
        5.81948292e-03, -1.26787318e-02, -1.98195828e-02,  8.70472373e-03,
       -2.09478019e-02, -6.99773735e-04,  2.65819900e-02, -1.03676287e-02,
       -2.90986242e-02,  1.68771319e-03,  2.65301955e-03, -6.35742428e-03,
       -1.75490051e-02, -1.44093628e-02, -2.45339692e-02,  2.29957717e-02,
        6.53496651e-03,  5.34828188e-03,  1.43952120e-02, -4.39635117e-03,
       -1.89490426e-02, -7.22528689e-03, -1.89405585e-02,  9.50228090e-03,
       -4.21855405e-03, -6.56804870e-03, -1.43757088e-03, -1.01589254e-02,
       -1.50883801e-02, -4.76854070e-03,  7.01199938e-03, -1.04522406e-02,
       -1.49345407e-02, -1.05202153e-02, -1.61487646e-02, -8.28348575e-03,
        1.50593232e-03, -8.79934750e-03,  2.20046139e-03, -9.52134326e-03,
       -6.01675996e-03, -1.37945605e-02, -1.57628782e-02, -1.49851147e-02,
        1.00176444e-02,  7.03252322e-03, -1.26938941e-02, -4.33922901e-03,
        1.98323641e-03, -3.78380292e-03, -1.48747157e-02,  5.04798847e-03,
       -1.34340355e-02, -8.21133085e-03, -1.64016520e-03,  7.45177037e-04,
       -7.15212585e-03, -7.02656001e-03, -1.46557307e-02,  2.59348268e-03,
       -1.94071280e-03,  1.18725814e-02, -1.12849045e-02, -2.24840814e-02,
        1.00906915e-02, -5.72501575e-06, -9.65300800e-03,  1.08807395e-02,
       -4.98639528e-03, -9.82102397e-03, -5.70268034e-03, -1.25384764e-02,
       -1.59688608e-02, -5.02792965e-03, -4.91961858e-03, -1.03581146e-03,
       -2.91031860e-03, -1.81010558e-02, -1.57855619e-03, -7.83325057e-03,
        4.37204113e-03, -9.65619368e-03, -1.12951269e-02,  3.67054296e-03,
       -5.42788718e-03, -5.60909252e-03,  4.28637403e-03,  4.33022563e-04,
       -1.01810547e-02, -1.49081915e-02, -1.84403491e-02, -8.53992557e-03,
       -5.18407142e-03, -5.15239482e-03, -6.42232116e-03, -1.34845975e-02,
       -9.87432435e-03, -1.36360033e-02, -3.10918019e-03, -8.93115278e-03,
       -6.20838086e-03, -6.06438496e-04,  1.06434634e-04, -1.78417895e-02,
       -4.04993177e-03,  8.71392763e-03, -1.10041918e-02, -1.04860128e-02,
       -2.14002789e-02,  8.51106607e-03, -6.00000719e-03, -1.53739473e-02,
       -6.15688176e-05, -6.53196518e-04, -1.38822168e-02, -2.12538772e-03,
        9.45214661e-03, -1.96796845e-02, -1.84952370e-02,  4.23052064e-04,
        1.86352412e-02,  1.76219979e-03, -2.50058849e-02,  6.09310530e-03,
        2.28960597e-03, -1.28338366e-02, -1.72040172e-02, -2.11838033e-02,
        1.82486458e-02, -5.09921947e-03, -1.35486605e-02,  2.44079097e-02,
        1.38069329e-02, -1.46947040e-02, -7.09399897e-03])

In [93]:
# Recordad métodos y atributos 

print(dir(ols_model))

# predict para ello uso la función predict 

ols_model.predict(X)

# acceso a los parámetros

ols_model.params

# R2 y R2  ajustado

ols_model.rsquared
ols_model.rsquared_adj

['HC0_se', 'HC1_se', 'HC2_se', 'HC3_se', '_HCCM', '__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_abat_diagonal', '_cache', '_data_attr', '_data_in_cache', '_get_robustcov_results', '_is_nested', '_use_t', '_wexog_singular_values', 'aic', 'bic', 'bse', 'centered_tss', 'compare_f_test', 'compare_lm_test', 'compare_lr_test', 'condition_number', 'conf_int', 'conf_int_el', 'cov_HC0', 'cov_HC1', 'cov_HC2', 'cov_HC3', 'cov_kwds', 'cov_params', 'cov_type', 'df_model', 'df_resid', 'diagn', 'eigenvals', 'el_test', 'ess', 'f_pvalue', 'f_test', 'fittedvalues', 'fvalue', 'get_influence', 'get_prediction', 'get_robustcov_results', 'info_criteria', 'initialize', 'k_constant', 'llf', 'load', 'model', 'mse_model', 'mse_resid', 'mse_total', 'nobs', 'normalized_cov_params', 'outlier_test', 'params', 'predict', 'pvalues', 'remove_data', 'resid', 'resid_pearson', 'rsquared', 'rsquared_adj', 'save', 'scale', 'ssr', 'summary', 'summary2', 't_test', 't_test_pairwise', 'tvalues', 'uncentered_tss', 'use_t', 'wald_test', 'wald_test_terms', 'wresid']

0.02088027937651482

In [94]:
control_formula = "gdp_g"+ " ~ "+ "GPCP_g + " + "GPCP_g_l"

ols_model = smf.ols(control_formula, data=repdata).fit()

print(ols_model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                  gdp_g   R-squared:                       0.024
Model:                            OLS   Adj. R-squared:                  0.021
Method:                 Least Squares   F-statistic:                     8.912
Date:                Sat, 12 Nov 2022   Prob (F-statistic):           0.000150
Time:                        01:17:10   Log-Likelihood:                 923.53
No. Observations:                 743   AIC:                            -1841.
Df Residuals:                     740   BIC:                            -1827.
Df Model:                           2
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     -0.0061      0.003     -2.375      0.018      -0.011      -0.001
GPCP_g         0.0554      0.013      4.126      0.000       0.029       0.082
GPCP_g_l       0.0341      0.014      2.502      0.013       0.007       0.061
==============================================================================
Omnibus:                      233.849   Durbin-Watson:                   1.912
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             8701.616
Skew:                           0.693   Prob(JB):                         0.00
Kurtosis:                      19.708   Cond. No.                         6.26
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

### Using sklearn (modelos ML lineales)

https://scikit-learn.org/stable/auto_examples/linear_model/plot_ols.html#sphx-glr-auto-examples-linear-model-plot-ols-py

In [97]:
ols_model_skl = linear_model.LinearRegression().fit( X, y )

ols_model_skl.coef_ # acceso a coeficientes 

ols_model_skl.predict(X) # predict en formato array 
ols_model_skl.score(X,y) # R cuadrado

0.023519415945896127

In [98]:
dir(ols_model_skl)

['__abstractmethods__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_abc_impl',
 '_check_feature_names',
 '_check_n_features',
 '_decision_function',
 '_estimator_type',
 '_get_param_names',
 '_get_tags',
 '_more_tags',
 '_preprocess_data',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_residues',
 '_set_intercept',
 '_validate_data',
 'coef_',
 'copy_X',
 'feature_names_in_',
 'fit',
 'fit_intercept',
 'get_params',
 'intercept_',
 'n_features_in_',
 'n_jobs',
 'normalize',
 'positive',
 'predict',
 'rank_',
 'score',
 'set_params',
 'singular_']

In [100]:
mean_squared_error( y, ols_model.predict())**0.5 # root mean square error

0.06981466645337808

## Modelo1 

- OLS, sin efectos fijos o country-time trend
- Robust errores estandar (Huber robust)
- Los residuos estan clusterizados (agrupados) a nivel país
-  Using cluster and robust standar error

In [101]:
control_formula = "gdp_g"+ " ~ "+ "GPCP_g + " + "GPCP_g_l"

ols_model1 = smf.ols(control_formula, data=repdata).fit(cov_type='cluster', cov_kwds={'groups': repdata['ccode']})

# cov_type='cluster', cov_kwds={'groups': repdata['ccode']}: cluster and robust standar error

print(ols_model1.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                  gdp_g   R-squared:                       0.024
Model:                            OLS   Adj. R-squared:                  0.021
Method:                 Least Squares   F-statistic:                     6.672
Date:                Sat, 12 Nov 2022   Prob (F-statistic):            0.00316
Time:                        01:18:37   Log-Likelihood:                 923.53
No. Observations:                 743   AIC:                            -1841.
Df Residuals:                     740   BIC:                            -1827.
Df Model:                           2
Covariance Type:              cluster
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     -0.0061      0.002     -2.499      0.012      -0.011      -0.001
GPCP_g         0.0554      0.016      3.400      0.001       0.023       0.087
GPCP_g_l       0.0341      0.013      2.578      0.010       0.008       0.060
==============================================================================
Omnibus:                      233.849   Durbin-Watson:                   1.912
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             8701.616
Skew:                           0.693   Prob(JB):                         0.00
Kurtosis:                      19.708   Cond. No.                         6.26
==============================================================================

Notes:
[1] Standard Errors are robust to cluster correlation (cluster)

In [102]:
print(ols_model1.summary().tables[1])

==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     -0.0061      0.002     -2.499      0.012      -0.011      -0.001
GPCP_g         0.0554      0.016      3.400      0.001       0.023       0.087
GPCP_g_l       0.0341      0.013      2.578      0.010       0.008       0.060
==============================================================================

In [106]:
print(mean_squared_error( y, ols_model1.predict())**0.5) # Root mean square error
ols_model1.rsquared  # R2 square 

rmse_ol1 = round(mean_squared_error( y, ols_model1.predict())**0.5,2)

0.06981466645337808

### Model2 OLS:

- No efectos fijos (country), Si country-time trends
- errores estandar robustas (Huber-White robust)
- termino de perturbación están clusterizados (agrupados) a nivel país
- Se añade variables de control

In [109]:
# Control variables 

control_vars = ["y_0", "polity2l", "ethfrac", "relfrac", "Oil", "lmtnest","lpopl1"]

# country fixed effect

index_columns = np.where( repdata.columns.str.contains(
    '_time$'))[0]
# indice con nombre de variables que terminan con _time

country_trend = repdata.columns[index_columns] # se extrae el nombre de todas las variables que terminan con _time

formula_model2 = "gdp_g"+ " ~ "+ "GPCP_g + " + "GPCP_g_l + " + ' + '.join( control_vars ) + ' + '.join( country_trend )

In [110]:
formula_model2

'gdp_g ~ GPCP_g + GPCP_g_l + y_0 + polity2l + ethfrac + relfrac + Oil + lmtnest + lpopl1ccode_404_time + ccode_420_time + ccode_432_time + ccode_433_time + ccode_434_time + ccode_435_time + ccode_436_time + ccode_437_time + ccode_438_time + ccode_439_time + ccode_450_time + ccode_451_time + ccode_452_time + ccode_461_time + ccode_471_time + ccode_475_time + ccode_481_time + ccode_482_time + ccode_483_time + ccode_484_time + ccode_490_time + ccode_500_time + ccode_501_time + ccode_510_time + ccode_516_time + ccode_517_time + ccode_520_time + ccode_522_time + ccode_530_time + ccode_540_time + ccode_541_time + ccode_551_time + ccode_552_time + ccode_553_time + ccode_560_time + ccode_565_time + ccode_570_time + ccode_571_time + ccode_572_time + ccode_580_time + ccode_625_time'