## Lab 10 : R y Python


### @autor: Roberto Mendoza

In [1]:
# import libraries 

import pandas as pd 
import numpy as np
import re 
from tqdm import tqdm  # controlar el tiempo en un loop
import os
import statsmodels.api as sm  # linear regression utiliza todas las columnas de base de datos 
import statsmodels.formula.api as smf  # linear regression usa uan formula
from stargazer.stargazer import Stargazer
from sklearn import datasets, linear_model # models 
from sklearn.metrics import mean_squared_error, r2_score
import econtools.metrics as mt  # for econoemtrics models 
import warnings
warnings.filterwarnings('ignore') # eliminar warning messages 

# !pip install stargazer

user = os.getlogin()   # Username
os.chdir(f"C:/Users/{user}/Documents/GitHub/1ECO35_2022_2/Lab10") # Set directorio

In [2]:
# laod dataset

repdata = pd.read_stata(r"../data/dataverse_files/mss_repdata.dta",
                           convert_categoricals=False)

repdata

,ccode,year,country_name,country_code,GPCP,GPCP_l,GPCP_l2,GPCP_g,GPCP_g_l,GPCP_g_fl,...,muni,state,author,stconst,fh_civ,fh_pol,S,W,WoverS,soc
0,540.0,1981-01-01,Angola,AGO,839.215759,911.847290,1021.776855,-0.079653,-0.107587,0.155680,...,0.0,1.0,NaN,NaN,0.000000,0.000000,1.0,0.5,0.500712,1.0
1,540.0,1982-01-01,Angola,AGO,969.864563,839.215759,911.847290,0.155680,-0.079653,-0.034482,...,0.0,1.0,NaN,NaN,0.000000,0.000000,1.0,0.5,0.500712,1.0
2,540.0,1983-01-01,Angola,AGO,936.421631,969.864563,839.215759,-0.034482,0.155680,0.059925,...,0.0,1.0,NaN,NaN,0.000000,0.000000,1.0,0.5,0.500712,1.0
3,540.0,1984-01-01,Angola,AGO,992.536255,936.421631,969.864563,0.059925,-0.034482,-0.018277,...,0.0,1.0,NaN,NaN,0.000000,0.000000,1.0,0.5,0.500712,1.0
4,540.0,1985-01-01,Angola,AGO,974.396118,992.536255,936.421631,-0.018277,0.059925,0.216019,...,0.0,1.0,NaN,NaN,0.000000,0.000000,1.0,0.5,0.500712,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
738,552.0,1995-01-01,Zimbabwe,ZWE,493.448456,465.000092,680.722412,0.061179,-0.316902,0.513642,...,NaN,0.0,NaN,NaN,0.333333,0.333333,1.0,0.5,0.500712,0.0
739,552.0,1996-01-01,Zimbabwe,ZWE,746.904236,493.448456,465.000092,0.513642,0.061179,0.044380,...,NaN,0.0,NaN,NaN,0.333333,0.333333,1.0,0.5,0.500712,0.0
740,552.0,1997-01-01,Zimbabwe,ZWE,780.051941,746.904236,493.448456,0.044380,0.513642,-0.181482,...,NaN,0.0,NaN,NaN,0.333333,0.333333,1.0,0.5,0.500712,0.0
741,552.0,1998-01-01,Zimbabwe,ZWE,638.486389,780.051941,746.904236,-0.181482,0.044380,0.094420,...,NaN,0.0,NaN,NaN,0.333333,0.333333,1.0,0.5,0.500712,0.0
742,552.0,1999-01-01,Zimbabwe,ZWE,698.772217,638.486389,780.051941,0.094420,-0.181482,0.428359,...,NaN,0.0,NaN,NaN,0.333333,0.166667,1.0,0.5,0.500712,0.0

In [3]:
# summmary statistics

repdata.describe()

# Tipo de variables

repdata.info()

repdata.dtypes

<class 'pandas.core.frame.DataFrame'>
Int64Index: 743 entries, 0 to 742
Columns: 200 entries, ccode to soc
dtypes: datetime64[ns](1), float32(104), float64(78), int32(9), int8(5), object(3)
memory usage: 813.4+ KB

ccode                  float64
year            datetime64[ns]
country_name            object
country_code            object
GPCP                   float32
                     ...
fh_pol                 float64
S                      float32
W                      float32
WoverS                 float32
soc                    float32
Length: 200, dtype: object

In [4]:
# Extraer year
# con month se puede extraer el mes 
# con day se puede extraer el día 

repdata['time_year'] = pd.DatetimeIndex(repdata['year']).year - 1978
repdata['time_year']

0       3
1       4
2       5
3       6
4       7
       ..
738    17
739    18
740    19
741    20
742    21
Name: time_year, Length: 743, dtype: int64

In [5]:
dummys = pd.get_dummies(repdata["ccode"].astype(int), prefix = "ccode", dummy_na=False)
dummys.columns

# se convierte a entero repdata["ccode"].astype(int)

Index(['ccode_404', 'ccode_420', 'ccode_432', 'ccode_433', 'ccode_434',
       'ccode_435', 'ccode_436', 'ccode_437', 'ccode_438', 'ccode_439',
       'ccode_450', 'ccode_451', 'ccode_452', 'ccode_461', 'ccode_471',
       'ccode_475', 'ccode_481', 'ccode_482', 'ccode_483', 'ccode_484',
       'ccode_490', 'ccode_500', 'ccode_501', 'ccode_510', 'ccode_516',
       'ccode_517', 'ccode_520', 'ccode_522', 'ccode_530', 'ccode_540',
       'ccode_541', 'ccode_551', 'ccode_552', 'ccode_553', 'ccode_560',
       'ccode_565', 'ccode_570', 'ccode_571', 'ccode_572', 'ccode_580',
       'ccode_625'],
      dtype='object')

In [6]:
len(dummys.columns)

41

##### Reference get_dummies

https://pandas.pydata.org/docs/reference/api/pandas.get_dummies.html

In [7]:
# Dummies a nivel país 

repdata = pd.concat([ repdata , dummys], axis = 1 )

In [8]:
repdata

,ccode,year,country_name,country_code,GPCP,GPCP_l,GPCP_l2,GPCP_g,GPCP_g_l,GPCP_g_fl,...,ccode_551,ccode_552,ccode_553,ccode_560,ccode_565,ccode_570,ccode_571,ccode_572,ccode_580,ccode_625
0,540.0,1981-01-01,Angola,AGO,839.215759,911.847290,1021.776855,-0.079653,-0.107587,0.155680,...,0,0,0,0,0,0,0,0,0,0
1,540.0,1982-01-01,Angola,AGO,969.864563,839.215759,911.847290,0.155680,-0.079653,-0.034482,...,0,0,0,0,0,0,0,0,0,0
2,540.0,1983-01-01,Angola,AGO,936.421631,969.864563,839.215759,-0.034482,0.155680,0.059925,...,0,0,0,0,0,0,0,0,0,0
3,540.0,1984-01-01,Angola,AGO,992.536255,936.421631,969.864563,0.059925,-0.034482,-0.018277,...,0,0,0,0,0,0,0,0,0,0
4,540.0,1985-01-01,Angola,AGO,974.396118,992.536255,936.421631,-0.018277,0.059925,0.216019,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
738,552.0,1995-01-01,Zimbabwe,ZWE,493.448456,465.000092,680.722412,0.061179,-0.316902,0.513642,...,0,1,0,0,0,0,0,0,0,0
739,552.0,1996-01-01,Zimbabwe,ZWE,746.904236,493.448456,465.000092,0.513642,0.061179,0.044380,...,0,1,0,0,0,0,0,0,0,0
740,552.0,1997-01-01,Zimbabwe,ZWE,780.051941,746.904236,493.448456,0.044380,0.513642,-0.181482,...,0,1,0,0,0,0,0,0,0,0
741,552.0,1998-01-01,Zimbabwe,ZWE,638.486389,780.051941,746.904236,-0.181482,0.044380,0.094420,...,0,1,0,0,0,0,0,0,0,0
742,552.0,1999-01-01,Zimbabwe,ZWE,698.772217,638.486389,780.051941,0.094420,-0.181482,0.428359,...,0,1,0,0,0,0,0,0,0,0

In [9]:
# Creación del trend_country effects

i = 0

while i < 41:  # 41 por el tema de indexing pues en python la posición inicial es cero. 
    var = dummys.columns[i]+"_"+"time"  # creamos el nombre de cada variable
    repdata[var]  = repdata[dummys.columns[i]]*repdata["time_year"] # multiplicacón de variables

    i = i + 1

In [10]:
repdata

,ccode,year,country_name,country_code,GPCP,GPCP_l,GPCP_l2,GPCP_g,GPCP_g_l,GPCP_g_fl,...,ccode_551_time,ccode_552_time,ccode_553_time,ccode_560_time,ccode_565_time,ccode_570_time,ccode_571_time,ccode_572_time,ccode_580_time,ccode_625_time
0,540.0,1981-01-01,Angola,AGO,839.215759,911.847290,1021.776855,-0.079653,-0.107587,0.155680,...,0,0,0,0,0,0,0,0,0,0
1,540.0,1982-01-01,Angola,AGO,969.864563,839.215759,911.847290,0.155680,-0.079653,-0.034482,...,0,0,0,0,0,0,0,0,0,0
2,540.0,1983-01-01,Angola,AGO,936.421631,969.864563,839.215759,-0.034482,0.155680,0.059925,...,0,0,0,0,0,0,0,0,0,0
3,540.0,1984-01-01,Angola,AGO,992.536255,936.421631,969.864563,0.059925,-0.034482,-0.018277,...,0,0,0,0,0,0,0,0,0,0
4,540.0,1985-01-01,Angola,AGO,974.396118,992.536255,936.421631,-0.018277,0.059925,0.216019,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
738,552.0,1995-01-01,Zimbabwe,ZWE,493.448456,465.000092,680.722412,0.061179,-0.316902,0.513642,...,0,17,0,0,0,0,0,0,0,0
739,552.0,1996-01-01,Zimbabwe,ZWE,746.904236,493.448456,465.000092,0.513642,0.061179,0.044380,...,0,18,0,0,0,0,0,0,0,0
740,552.0,1997-01-01,Zimbabwe,ZWE,780.051941,746.904236,493.448456,0.044380,0.513642,-0.181482,...,0,19,0,0,0,0,0,0,0,0
741,552.0,1998-01-01,Zimbabwe,ZWE,638.486389,780.051941,746.904236,-0.181482,0.044380,0.094420,...,0,20,0,0,0,0,0,0,0,0
742,552.0,1999-01-01,Zimbabwe,ZWE,698.772217,638.486389,780.051941,0.094420,-0.181482,0.428359,...,0,21,0,0,0,0,0,0,0,0

In [11]:
table1 = repdata.loc[:,["any_prio", "any_prio_on", "any_prio_off","war_prio", "war_prio_on", "war_prio_off",
                        "war_col", "war_inc", "war","GPCP", "GPCP_g", "GPCP_g_l","gdp_g", "gdp_g_l",
        "y_0", "polity2l", "polity2l_6", "ethfrac", "relfrac", "Oil", "lmtnest", "lpopl1", "tot_100_g"]]

table1

,any_prio,any_prio_on,any_prio_off,war_prio,war_prio_on,war_prio_off,war_col,war_inc,war,GPCP,...,gdp_g_l,y_0,polity2l,polity2l_6,ethfrac,relfrac,Oil,lmtnest,lpopl1,tot_100_g
0,1.0,NaN,0.0,1.0,NaN,0.0,1.0,1.0,1.0,839.215759,...,0.019637,0.662,-7.0,0.0,0.783282,0.6122,1.0,2.370244,8.933400,NaN
1,1.0,NaN,0.0,1.0,NaN,0.0,1.0,1.0,1.0,969.864563,...,-0.037037,0.662,-7.0,0.0,0.783282,0.6122,1.0,2.370244,8.959697,NaN
2,1.0,NaN,0.0,1.0,NaN,0.0,1.0,1.0,1.0,936.421631,...,0.044615,0.662,-7.0,0.0,0.783282,0.6122,1.0,2.370244,8.985946,NaN
3,1.0,NaN,0.0,1.0,NaN,0.0,1.0,1.0,1.0,992.536255,...,-0.008837,0.662,-7.0,0.0,0.783282,0.6122,1.0,2.370244,9.012134,NaN
4,1.0,NaN,0.0,1.0,NaN,0.0,1.0,1.0,1.0,974.396118,...,0.026746,0.662,-7.0,0.0,0.783282,0.6122,1.0,2.370244,9.035987,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
738,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,0.0,493.448456,...,0.030296,1.190,-6.0,0.0,0.543950,0.5098,0.0,1.360977,9.285019,-0.006359
739,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,0.0,746.904236,...,-0.018779,1.190,-6.0,0.0,0.543950,0.5098,0.0,1.360977,9.306650,0.001000
740,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,0.0,780.051941,...,0.078490,1.190,-6.0,0.0,0.543950,0.5098,0.0,1.360977,9.327418,0.095405
741,1.0,1.0,NaN,1.0,1.0,NaN,0.0,0.0,0.0,638.486389,...,0.008137,1.190,-6.0,0.0,0.543950,0.5098,0.0,1.360977,9.347324,-0.006019
742,1.0,NaN,0.0,1.0,NaN,0.0,0.0,0.0,0.0,698.772217,...,0.017494,1.190,-6.0,0.0,0.543950,0.5098,0.0,1.360977,9.366368,-0.079282

In [12]:
summary_table = table1.describe().loc[["mean","std","count"]].T

In [13]:
table1.columns

new_names = ["Civil conflict with ≥25 deaths: (PRIO/Uppsala)","Onset","Offset",
"Civil conflict with ≥1,000 deaths:PRIO/Uppsala","Onset","Offset","Collier and Hoeffler (2002)",  
"Doyle and Sambanis (2000)","Fearon and Laitin (2003)",
"Annual rainfall (mm), GPCP measure",
"Annual growth in rainfall, time t",
"Annual growth in rainfall, time t-1",
"Annual economic growth rate, time t",
"Annual economic growth rate, time t-1",
"Log(GDP per capita), 1979",
"Democracy level (Polity IV score, -10 to 10), time t-1",
"Democracy indicator (Polity IV score > 15),time t-1",
"Ethnolinguistic fractionalization (source:Atlas Marodov Mira)",
"Religious fractionalization (source: CIAFactbook)",
"Oil-exporting country (source: WDI)",
"Log(mountainous) (source: Fearon and Laitin 2003)",
"Log(national population), time t-1 (source: WDI)",
"Growth in terms of trade, time t (source:WDI)"]

# unión de listas bajo la estructura diccionario

dict( zip( table1.columns, new_names) )

{'any_prio': 'Civil conflict with ≥25 deaths: (PRIO/Uppsala)',
 'any_prio_on': 'Onset',
 'any_prio_off': 'Offset',
 'war_prio': 'Civil conflict with ≥1,000 deaths:PRIO/Uppsala',
 'war_prio_on': 'Onset',
 'war_prio_off': 'Offset',
 'war_col': 'Collier and Hoeffler (2002)',
 'war_inc': 'Doyle and Sambanis (2000)',
 'war': 'Fearon and Laitin (2003)',
 'GPCP': 'Annual rainfall (mm), GPCP measure',
 'GPCP_g': 'Annual growth in rainfall, time t',
 'GPCP_g_l': 'Annual growth in rainfall, time t-1',
 'gdp_g': 'Annual economic growth rate, time t',
 'gdp_g_l': 'Annual economic growth rate, time t-1',
 'y_0': 'Log(GDP per capita), 1979',
 'polity2l': 'Democracy level (Polity IV score, -10 to 10), time t-1',
 'polity2l_6': 'Democracy indicator (Polity IV score > 15),time t-1',
 'ethfrac': 'Ethnolinguistic fractionalization (source:Atlas Marodov Mira)',
 'relfrac': 'Religious fractionalization (source: CIAFactbook)',
 'Oil': 'Oil-exporting country (source: WDI)',
 'lmtnest': 'Log(mountainous) (source: Fearon and Laitin 2003)',
 'lpopl1': 'Log(national population), time t-1 (source: WDI)',
 'tot_100_g': 'Growth in terms of trade, time t (source:WDI)'}

In [14]:
# Customize summary table 

index = dict( zip( table1.columns, new_names) )

columns = {
    "mean": "Mean",
    "std": "Standard Deviation",
    "count": "Observations",
}

formatters = {
    "mean": "{:.2f}".format,
    "std": "{:.2f}".format,
    "count": "{:.0f}".format,
}

# Rename rows (indexes) and columns
summary_table.rename(index=index, columns=columns, inplace=True)

# Export the DataFrame to LaTeX
summary_table.to_latex(
    "summary.tex",
    formatters={columns[c]: f for c, f in formatters.items()},
    index_names=False,
    column_format = "lccc",
    caption = "Descriptive Statistics"
)

In [15]:

#Columns format

summary_table.style.format(subset="Mean", precision=2).format(subset="Standard Deviation", precision=2).format(subset="Observations", precision=0)


# Export the DataFrame to LaTeX
# \ permite esccribir código extenso en lineas diferentes

summary_table.style.format(subset="Mean", precision=2).format(subset="Standard Deviation", precision=2)\
.format(subset="Observations", precision=0)\
.to_latex(
    "summary2.tex",
caption="Descriptive Statistics",
    column_format = "lccc"
)

In [16]:
summary_table.style.format(subset="Mean", precision=2).format(subset="Standard Deviation", precision=2).format(subset="Observations", precision=0)

## First stage

#### Linear models libraries

https://www.statsmodels.org/stable/index.html

https://github.com/vgreg/python-se/blob/master/Standard%20errors%20in%20Python.ipynb

In [17]:

# add constant

y = repdata['gdp_g']

X = sm.add_constant(repdata.loc[:,["GPCP_g", "GPCP_g_l"]])

# sm function

ols_model = sm.OLS(y, X).fit()

# fit permite correr la regresión

print(ols_model.summary())

# Robust standar error

ols_model_rb = sm.OLS(y, X).fit().get_robustcov_results(cov_type = "HC1")
print(ols_model_rb.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                  gdp_g   R-squared:                       0.024
Model:                            OLS   Adj. R-squared:                  0.021
Method:                 Least Squares   F-statistic:                     8.912
Date:                Wed, 09 Nov 2022   Prob (F-statistic):           0.000150
Time:                        17:40:53   Log-Likelihood:                 923.53
No. Observations:                 743   AIC:                            -1841.
Df Residuals:                     740   BIC:                            -1827.
Df Model:                           2
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         -0.0061      0.003     -2.375      0.018      -0.011      -0.001
GPCP_g         0.0554      0.013      4.126      0.000       0.029       0.082
GPCP_g_l       0.0341      0.014      2.502      0.013       0.007       0.061
==============================================================================
Omnibus:                      233.849   Durbin-Watson:                   1.912
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             8701.616
Skew:                           0.693   Prob(JB):                         0.00
Kurtosis:                      19.708   Cond. No.                         6.26
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
                            OLS Regression Results
==============================================================================
Dep. Variable:                  gdp_g   R-squared:                       0.024
Model:                            OLS   Adj. R-squared:                  0.021
Method:                 Least Squares   F-statistic:                     8.703
Date:                Wed, 09 Nov 2022   Prob (F-statistic):           0.000184
Time:                        17:40:53   Log-Likelihood:                 923.53
No. Observations:                 743   AIC:                            -1841.
Df Residuals:                     740   BIC:                            -1827.
Df Model:                           2
Covariance Type:                  HC1
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         -0.0061      0.003     -2.349      0.019      -0.011      -0.001
GPCP_g         0.0554      0.014      3.909      0.000       0.028       0.083
GPCP_g_l       0.0341      0.012      2.862      0.004       0.011       0.057
==============================================================================
Omnibus:                      233.849   Durbin-Watson:                   1.912
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             8701.616
Skew:                           0.693   Prob(JB):                         0.00
Kurtosis:                      19.708   Cond. No.                         6.26
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC1)

In [18]:
#alternative robust standar error

ols_model_rb0 = sm.OLS(y, X).fit().get_robustcov_results(cov_type = "HC0") # White robust se
ols_model_rb1 = sm.OLS(y, X).fit().get_robustcov_results(cov_type = "HC1") # Huber-White robust se
ols_model_rb2 = sm.OLS(y, X).fit().get_robustcov_results(cov_type = "HC2") # Eicker-Huber-White robust
ols_model_rb3 = sm.OLS(y, X).fit().get_robustcov_results(cov_type = "HC3")

print(ols_model_rb3.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                  gdp_g   R-squared:                       0.024
Model:                            OLS   Adj. R-squared:                  0.021
Method:                 Least Squares   F-statistic:                     8.425
Date:                Wed, 09 Nov 2022   Prob (F-statistic):           0.000241
Time:                        17:40:53   Log-Likelihood:                 923.53
No. Observations:                 743   AIC:                            -1841.
Df Residuals:                     740   BIC:                            -1827.
Df Model:                           2
Covariance Type:                  HC3
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         -0.0061      0.003     -2.345      0.019      -0.011      -0.001
GPCP_g         0.0554      0.014      3.826      0.000       0.027       0.084
GPCP_g_l       0.0341      0.012      2.845      0.005       0.011       0.058
==============================================================================
Omnibus:                      233.849   Durbin-Watson:                   1.912
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             8701.616
Skew:                           0.693   Prob(JB):                         0.00
Kurtosis:                      19.708   Cond. No.                         6.26
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC3)

In [19]:
# Acceder a la información de la tabla

ols_model_rb.summary2()

ols_model_rb.summary2().tables[1]

             Coef.  Std.Err.         t     P>|t|    [0.025    0.975]
const    -0.006147  0.002617 -2.348553  0.019109 -0.011285 -0.001009
GPCP_g    0.055430  0.014180  3.908990  0.000101  0.027592  0.083268
GPCP_g_l  0.034058  0.011901  2.861785  0.004332  0.010694  0.057422

In [20]:
dir(sm.OLS(y, X))

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_check_kwargs',
 '_data_attr',
 '_df_model',
 '_df_resid',
 '_fit_collinear',
 '_fit_ridge',
 '_fit_zeros',
 '_formula_max_endog',
 '_get_init_kwds',
 '_handle_data',
 '_init_keys',
 '_kwargs_allowed',
 '_setup_score_hess',
 '_sqrt_lasso',
 'data',
 'df_model',
 'df_resid',
 'endog',
 'endog_names',
 'exog',
 'exog_names',
 'fit',
 'fit_regularized',
 'from_formula',
 'get_distribution',
 'hessian',
 'hessian_factor',
 'information',
 'initialize',
 'k_constant',
 'loglike',
 'nobs',
 'predict',
 'rank',
 'score',
 'weights',
 'wendog',
 'wexog',
 'whiten']

In [21]:
# Recordad métodos y atributos 

dir(sm.OLS(y, X))

# predict para ello uso la función predict 

ols_model.predict(X)

# acceso a los parámetros

ols_model.params

# R2 y R2  ajustado

ols_model.rsquared
ols_model.rsquared_adj

0.02088027937651482

In [22]:
control_formula = "gdp_g"+ " ~ "+ "GPCP_g + " + "GPCP_g_l"

ols_model = smf.ols(control_formula, data=repdata).fit()

print(ols_model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                  gdp_g   R-squared:                       0.024
Model:                            OLS   Adj. R-squared:                  0.021
Method:                 Least Squares   F-statistic:                     8.912
Date:                Wed, 09 Nov 2022   Prob (F-statistic):           0.000150
Time:                        17:40:53   Log-Likelihood:                 923.53
No. Observations:                 743   AIC:                            -1841.
Df Residuals:                     740   BIC:                            -1827.
Df Model:                           2
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     -0.0061      0.003     -2.375      0.018      -0.011      -0.001
GPCP_g         0.0554      0.013      4.126      0.000       0.029       0.082
GPCP_g_l       0.0341      0.014      2.502      0.013       0.007       0.061
==============================================================================
Omnibus:                      233.849   Durbin-Watson:                   1.912
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             8701.616
Skew:                           0.693   Prob(JB):                         0.00
Kurtosis:                      19.708   Cond. No.                         6.26
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [23]:
# ´predict 

ols_model.predict(X)

0     -0.014226
1     -0.000230
2     -0.002756
3     -0.004000
4     -0.005119
         ...
738   -0.013549
739    0.024408
740    0.013807
741   -0.014695
742   -0.007094
Length: 743, dtype: float64

### Using sklearn (modelos ML lineales)

https://scikit-learn.org/stable/auto_examples/linear_model/plot_ols.html#sphx-glr-auto-examples-linear-model-plot-ols-py

In [24]:
ols_model_skl = linear_model.LinearRegression().fit( X, y )

ols_model_skl.coef_ # acceso a coeficientes 

ols_model_skl.predict(X) # predict en formato array 
ols_model_skl.score(X,y) # R cuadrado

0.023519415945896127

In [25]:
dir(ols_model_skl)

['__abstractmethods__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_abc_impl',
 '_check_feature_names',
 '_check_n_features',
 '_decision_function',
 '_estimator_type',
 '_get_param_names',
 '_get_tags',
 '_more_tags',
 '_preprocess_data',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_residues',
 '_set_intercept',
 '_validate_data',
 'coef_',
 'copy_X',
 'feature_names_in_',
 'fit',
 'fit_intercept',
 'get_params',
 'intercept_',
 'n_features_in_',
 'n_jobs',
 'normalize',
 'positive',
 'predict',
 'rank_',
 'score',
 'set_params',
 'singular_']

In [26]:
mean_squared_error( y, ols_model.predict(X))**0.5 # root mean square error

0.06981466645337808

## Modelo1 

- OLS, sin efectos fijos o country-time trend
- Robust errores estandar (Huber robust)
- Los residuos estan clusterizados (agrupados) a nivel país
-  Using cluster and robust standar error

In [27]:
formula_model1 = "gdp_g"+ " ~ "+ "GPCP_g + " + "GPCP_g_l"

ols_model1 = smf.ols(formula_model1, data=repdata).fit(cov_type="HC1").\
get_robustcov_results(cov_type = "cluster", groups= repdata['ccode'])       # cluster terminos de perturbación
print(ols_model1.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                  gdp_g   R-squared:                       0.024
Model:                            OLS   Adj. R-squared:                  0.021
Method:                 Least Squares   F-statistic:                     6.672
Date:                Wed, 09 Nov 2022   Prob (F-statistic):            0.00316
Time:                        17:40:53   Log-Likelihood:                 923.53
No. Observations:                 743   AIC:                            -1841.
Df Residuals:                     740   BIC:                            -1827.
Df Model:                           2
Covariance Type:              cluster
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     -0.0061      0.002     -2.499      0.012      -0.011      -0.001
GPCP_g         0.0554      0.016      3.400      0.001       0.023       0.087
GPCP_g_l       0.0341      0.013      2.578      0.010       0.008       0.060
==============================================================================
Omnibus:                      233.849   Durbin-Watson:                   1.912
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             8701.616
Skew:                           0.693   Prob(JB):                         0.00
Kurtosis:                      19.708   Cond. No.                         6.26
==============================================================================

Notes:
[1] Standard Errors are robust to cluster correlation (cluster)

In [28]:
print(ols_model1.summary().tables[1])

==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     -0.0061      0.002     -2.499      0.012      -0.011      -0.001
GPCP_g         0.0554      0.016      3.400      0.001       0.023       0.087
GPCP_g_l       0.0341      0.013      2.578      0.010       0.008       0.060
==============================================================================

In [37]:
print(mean_squared_error( y, ols_model1.predict(X))**0.5) # Root mean square error
ols_model1.rsquared  # R2 square 

rms_model1 = mean_squared_error( y, ols_model1.predict(X))**0.5

0.06981466645337808

### Model2 OLS:

- No efectos fijos (country), Si country-time trends
- errores estandar robustas (Huber-White robust)
- termino de perturbación están clusterizados (agrupados) a nivel país
- Se añade variables de control

In [39]:
# Control variables 

control_vars = ["y_0", "polity2l", "ethfrac", "relfrac", "Oil", "lmtnest","lpopl1"]

# country fixed effect

index_columns = np.where( repdata.columns.str.contains('_time$'))[0]

country_trend = repdata.columns[index_columns]

formula_model2 = "gdp_g"+ " ~ "+ "GPCP_g + " + "GPCP_g_l + " + ' + '.join( control_vars ) +' + ' + ' + '.join( country_trend )

In [40]:
formula_model2

'gdp_g ~ GPCP_g + GPCP_g_l + y_0 + polity2l + ethfrac + relfrac + Oil + lmtnest + lpopl1 + ccode_404_time + ccode_420_time + ccode_432_time + ccode_433_time + ccode_434_time + ccode_435_time + ccode_436_time + ccode_437_time + ccode_438_time + ccode_439_time + ccode_450_time + ccode_451_time + ccode_452_time + ccode_461_time + ccode_471_time + ccode_475_time + ccode_481_time + ccode_482_time + ccode_483_time + ccode_484_time + ccode_490_time + ccode_500_time + ccode_501_time + ccode_510_time + ccode_516_time + ccode_517_time + ccode_520_time + ccode_522_time + ccode_530_time + ccode_540_time + ccode_541_time + ccode_551_time + ccode_552_time + ccode_553_time + ccode_560_time + ccode_565_time + ccode_570_time + ccode_571_time + ccode_572_time + ccode_580_time + ccode_625_time'

In [41]:
ols_model2 = smf.ols(formula_model2, data=repdata).fit(cov_type="HC1").\
get_robustcov_results(cov_type = "cluster", groups= repdata['ccode'])       # cluster terminos de perturbación
print(ols_model2.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                  gdp_g   R-squared:                       0.081
Model:                            OLS   Adj. R-squared:                  0.014
Method:                 Least Squares   F-statistic:                     1.858
Date:                Wed, 09 Nov 2022   Prob (F-statistic):             0.0812
Time:                        22:05:00   Log-Likelihood:                 945.89
No. Observations:                 743   AIC:                            -1790.
Df Residuals:                     692   BIC:                            -1555.
Df Model:                          50
Covariance Type:              cluster
==================================================================================
                     coef    std err          z      P>|z|      [0.025      0.975]
----------------------------------------------------------------------------------
Intercept          0.0439      0.064      0.684      0.494      -0.082       0.170
GPCP_g             0.0530      0.017      3.154      0.002       0.020       0.086
GPCP_g_l           0.0320      0.014      2.371      0.018       0.006       0.058
y_0               -0.0109      0.007     -1.572      0.116      -0.024       0.003
polity2l        2.834e-05      0.001      0.041      0.967      -0.001       0.001
ethfrac            0.0057      0.044      0.130      0.896      -0.080       0.092
relfrac            0.0454      0.044      1.027      0.305      -0.041       0.132
Oil                0.0067      0.019      0.354      0.723      -0.030       0.044
lmtnest            0.0008      0.005      0.152      0.879      -0.010       0.011
lpopl1            -0.0087      0.009     -1.002      0.316      -0.026       0.008
ccode_404_time    -0.0012      0.002     -0.780      0.435      -0.004       0.002
ccode_420_time     0.0007      0.001      0.492      0.622      -0.002       0.003
ccode_432_time     0.0022      0.001      2.272      0.023       0.000       0.004
ccode_433_time     0.0027      0.001      2.717      0.007       0.001       0.005
ccode_434_time     0.0015      0.001      1.844      0.065   -9.32e-05       0.003
ccode_435_time     0.0025      0.001      1.840      0.066      -0.000       0.005
ccode_436_time    -0.0002      0.001     -0.249      0.803      -0.002       0.001
ccode_437_time     0.0013      0.001      1.415      0.157      -0.001       0.003
ccode_438_time     0.0022      0.001      2.586      0.010       0.001       0.004
ccode_439_time     0.0014      0.001      1.450      0.147      -0.000       0.003
ccode_450_time    -0.0024      0.002     -1.269      0.205      -0.006       0.001
ccode_451_time    -0.0027      0.001     -3.856      0.000      -0.004      -0.001
ccode_452_time     0.0021      0.001      1.624      0.104      -0.000       0.005
ccode_461_time -5.373e-05      0.001     -0.071      0.943      -0.002       0.001
ccode_471_time    -0.0003      0.001     -0.360      0.719      -0.002       0.001
ccode_475_time     0.0013      0.002      0.736      0.461      -0.002       0.005
ccode_481_time     0.0022      0.001      1.447      0.148      -0.001       0.005
ccode_482_time    -0.0009      0.001     -0.656      0.512      -0.004       0.002
ccode_483_time    -0.0004      0.001     -0.400      0.690      -0.002       0.002
ccode_484_time    -0.0009      0.001     -0.612      0.541      -0.004       0.002
ccode_490_time    -0.0029      0.001     -2.694      0.007      -0.005      -0.001
ccode_500_time     0.0022      0.001      2.037      0.042    8.15e-05       0.004
ccode_501_time     0.0011      0.001      0.977      0.329      -0.001       0.003
ccode_510_time     0.0016      0.001      1.442      0.149      -0.001       0.004
ccode_516_time    -0.0008      0.001     -0.539      0.590      -0.004       0.002
ccode_517_time     0.0010      0.001      0.813      0.416      -0.001       0.004
ccode_520_time     0.0020      0.003      0.681      0.496      -0.004       0.008
ccode_522_time     0.0031      0.003      1.055      0.291      -0.003       0.009
ccode_530_time     0.0021      0.001      1.598      0.110      -0.000       0.005
ccode_540_time    -0.0008      0.001     -0.686      0.493      -0.003       0.001
ccode_541_time     0.0028      0.001      2.858      0.004       0.001       0.005
ccode_551_time    -0.0002      0.001     -0.298      0.766      -0.002       0.001
ccode_552_time     0.0017      0.001      2.075      0.038    9.22e-05       0.003
ccode_553_time     0.0010      0.001      1.273      0.203      -0.001       0.003
ccode_560_time     0.0035      0.002      1.606      0.108      -0.001       0.008
ccode_565_time     0.0012      0.001      0.866      0.387      -0.001       0.004
ccode_570_time     0.0011      0.001      0.930      0.352      -0.001       0.004
ccode_571_time     0.0019      0.001      1.736      0.082      -0.000       0.004
ccode_572_time     0.0014      0.001      1.384      0.167      -0.001       0.003
ccode_580_time     0.0003      0.002      0.141      0.888      -0.003       0.004
ccode_625_time     0.0037      0.001      4.060      0.000       0.002       0.006
==============================================================================
Omnibus:                      247.374   Durbin-Watson:                   2.024
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            10770.483
Skew:                           0.731   Prob(JB):                         0.00
Kurtosis:                      21.595   Cond. No.                         206.
==============================================================================

Notes:
[1] Standard Errors are robust to cluster correlation (cluster)

In [45]:
rms_model2 = mean_squared_error( y, ols_model2.predict())**0.5

In [46]:
rms_model2

0.0677448615190589