In [13]:
from IPython.display import display, HTML

display(HTML(data="""
<style>
    div#notebook-container    { width: 75%; }
    div#menubar-container     { width: 80%; }
    div#maintoolbar-container { width: 80%; }a
</style>
"""))

In [1]:
'''
Importar librerias
- numpy para operaciones de vectores y matrices
- pandas para manipular DataFrame (base de datos)
- Series para manipular columnas de DataFrame 
'''

import numpy as np
import pandas as pd
from pandas import DataFrame,Series

In [14]:
# importar el csv almacenada en la carpeta data
# relative path ../ salir de la carpeta Lab3
# /data ingresar a la carpeta data

netflix = pd.read_csv("../data/netflix_titles.csv") # pro default UTF-8 para caracteres especiales y lectura de missing 
netflix

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,TV Show,3%,NaN,"João Miguel, Bianca Comparato, Michel Gomes, R...",Brazil,"August 14, 2020",2020,TV-MA,4 Seasons,"International TV Shows, TV Dramas, TV Sci-Fi &...",In a future where the elite inhabit an island ...
1,s2,Movie,7:19,Jorge Michel Grau,"Demián Bichir, Héctor Bonilla, Oscar Serrano, ...",Mexico,"December 23, 2016",2016,TV-MA,93 min,"Dramas, International Movies",After a devastating earthquake hits Mexico Cit...
2,s3,Movie,23:59,Gilbert Chan,"Tedd Chan, Stella Chung, Henley Hii, Lawrence ...",Singapore,"December 20, 2018",2011,R,78 min,"Horror Movies, International Movies","When an army recruit is found dead, his fellow..."
3,s4,Movie,9,Shane Acker,"Elijah Wood, John C. Reilly, Jennifer Connelly...",United States,"November 16, 2017",2009,PG-13,80 min,"Action & Adventure, Independent Movies, Sci-Fi...","In a postapocalyptic world, rag-doll robots hi..."
4,s5,Movie,21,Robert Luketic,"Jim Sturgess, Kevin Spacey, Kate Bosworth, Aar...",United States,"January 1, 2020",2008,PG-13,123 min,Dramas,A brilliant group of students become card-coun...
...,...,...,...,...,...,...,...,...,...,...,...,...
7782,s7783,Movie,Zozo,Josef Fares,"Imad Creidi, Antoinette Turk, Elias Gergi, Car...","Sweden, Czech Republic, United Kingdom, Denmar...","October 19, 2020",2005,TV-MA,99 min,"Dramas, International Movies",When Lebanon's Civil War deprives Zozo of his ...
7783,s7784,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...
7784,s7785,Movie,Zulu Man in Japan,NaN,Nasty C,NaN,"September 25, 2020",2019,TV-MA,44 min,"Documentaries, International Movies, Music & M...","In this documentary, South African rapper Nast..."
7785,s7786,TV Show,Zumbo's Just Desserts,NaN,"Adriano Zumbo, Rachel Khoo",Australia,"October 31, 2020",2019,TV-PG,1 Season,"International TV Shows, Reality TV",Dessert wizard Adriano Zumbo looks for the nex...
7786,s7787,Movie,ZZ TOP: THAT LITTLE OL' BAND FROM TEXAS,Sam Dunn,NaN,"United Kingdom, Canada, United States","March 1, 2020",2019,TV-MA,90 min,"Documentaries, Music & Musicals",This documentary delves into the mystique behi...

In [15]:
netflix.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,TV Show,3%,NaN,"João Miguel, Bianca Comparato, Michel Gomes, R...",Brazil,"August 14, 2020",2020,TV-MA,4 Seasons,"International TV Shows, TV Dramas, TV Sci-Fi &...",In a future where the elite inhabit an island ...
1,s2,Movie,7:19,Jorge Michel Grau,"Demián Bichir, Héctor Bonilla, Oscar Serrano, ...",Mexico,"December 23, 2016",2016,TV-MA,93 min,"Dramas, International Movies",After a devastating earthquake hits Mexico Cit...
2,s3,Movie,23:59,Gilbert Chan,"Tedd Chan, Stella Chung, Henley Hii, Lawrence ...",Singapore,"December 20, 2018",2011,R,78 min,"Horror Movies, International Movies","When an army recruit is found dead, his fellow..."
3,s4,Movie,9,Shane Acker,"Elijah Wood, John C. Reilly, Jennifer Connelly...",United States,"November 16, 2017",2009,PG-13,80 min,"Action & Adventure, Independent Movies, Sci-Fi...","In a postapocalyptic world, rag-doll robots hi..."
4,s5,Movie,21,Robert Luketic,"Jim Sturgess, Kevin Spacey, Kate Bosworth, Aar...",United States,"January 1, 2020",2008,PG-13,123 min,Dramas,A brilliant group of students become card-coun...

In [4]:
netflix.info() # varaible's type 

print( netflix.shape ) # filas y columnas

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7787 entries, 0 to 7786
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       7787 non-null   object
 1   type          7787 non-null   object
 2   title         7787 non-null   object
 3   director      5398 non-null   object
 4   cast          7069 non-null   object
 5   country       7280 non-null   object
 6   date_added    7777 non-null   object
 7   release_year  7787 non-null   int64
 8   rating        7780 non-null   object
 9   duration      7787 non-null   object
 10  listed_in     7787 non-null   object
 11  description   7787 non-null   object
dtypes: int64(1), object(11)
memory usage: 730.2+ KB
(7787, 12)

In [6]:
'''
Equivalent sum de Stata, solo la variable release_year es numerica
'''

netflix.describe()

       release_year
count   7787.000000
mean    2013.932580
std        8.757395
min     1925.000000
25%     2013.000000
50%     2017.000000
75%     2018.000000
max     2021.000000

In [64]:
## Verificando ID


print( netflix.show_id.unique() )

print( len( netflix.show_id.unique() ) )

print( netflix.show_id.is_unique )  # trueo false


##################################



# print( len(netflix['show_id'].unique() ) )

# netflix['show_id'].unique()

# netflix['show_id'].is_unique # verificando repeticiones

['s1' 's2' 's3' ... 's7785' 's7786' 's7787']
7787
True

In [24]:
netflix.release_year.is_unique

False

In [21]:
len( netflix.show_id.unique() )

7787

In [18]:
netflix.show_id

0          s1
1          s2
2          s3
3          s4
4          s5
        ...
7782    s7783
7783    s7784
7784    s7785
7785    s7786
7786    s7787
Name: show_id, Length: 7787, dtype: object

In [28]:
netflix[['director']]

               director
0                   NaN
1     Jorge Michel Grau
2          Gilbert Chan
3           Shane Acker
4        Robert Luketic
...                 ...
7782        Josef Fares
7783        Mozez Singh
7784                NaN
7785                NaN
7786           Sam Dunn

[7787 rows x 1 columns]

### ***Exploring a DataFrame***:

In [27]:
# Series en Python

print(type(netflix['director']))

netflix['director']
netflix.director

<class 'pandas.core.series.Series'>

0                     NaN
1       Jorge Michel Grau
2            Gilbert Chan
3             Shane Acker
4          Robert Luketic
              ...
7782          Josef Fares
7783          Mozez Singh
7784                  NaN
7785                  NaN
7786             Sam Dunn
Name: director, Length: 7787, dtype: object

In [29]:
## revisado missing values (NaN in Python)

print( netflix.director.unique() )
print( netflix.director.is_unique )

## isnull() and isna() son similares 

print( netflix.director.isnull() )

print( netflix['director'].isna() )

[nan 'Jorge Michel Grau' 'Gilbert Chan' ... 'Josef Fares' 'Mozez Singh'
 'Sam Dunn']
False
0        True
1       False
2       False
3       False
4       False
        ...
7782    False
7783    False
7784     True
7785     True
7786    False
Name: director, Length: 7787, dtype: bool
0        True
1       False
2       False
3       False
4       False
        ...
7782    False
7783    False
7784     True
7785     True
7786    False
Name: director, Length: 7787, dtype: bool

In [30]:
# cantidad de missing values en la variables director
print( netflix['director'].isna().sum() )

# Borrar missing values 

netflix.dropna() # borra todas las filas o columnas con al menos un missing value
netflix.dropna(axis = 0) # borras filas con missing value  , axis = 0 : aplicar función por filas
netflix.dropna(axis = 1) # borra columnas con al menos un missign values, axis = 1: aplicar función por columnas 

netflix.drop('listed_in', axis = 1)

2389

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,description
0,s1,TV Show,3%,NaN,"João Miguel, Bianca Comparato, Michel Gomes, R...",Brazil,"August 14, 2020",2020,TV-MA,4 Seasons,In a future where the elite inhabit an island ...
1,s2,Movie,7:19,Jorge Michel Grau,"Demián Bichir, Héctor Bonilla, Oscar Serrano, ...",Mexico,"December 23, 2016",2016,TV-MA,93 min,After a devastating earthquake hits Mexico Cit...
2,s3,Movie,23:59,Gilbert Chan,"Tedd Chan, Stella Chung, Henley Hii, Lawrence ...",Singapore,"December 20, 2018",2011,R,78 min,"When an army recruit is found dead, his fellow..."
3,s4,Movie,9,Shane Acker,"Elijah Wood, John C. Reilly, Jennifer Connelly...",United States,"November 16, 2017",2009,PG-13,80 min,"In a postapocalyptic world, rag-doll robots hi..."
4,s5,Movie,21,Robert Luketic,"Jim Sturgess, Kevin Spacey, Kate Bosworth, Aar...",United States,"January 1, 2020",2008,PG-13,123 min,A brilliant group of students become card-coun...
...,...,...,...,...,...,...,...,...,...,...,...
7782,s7783,Movie,Zozo,Josef Fares,"Imad Creidi, Antoinette Turk, Elias Gergi, Car...","Sweden, Czech Republic, United Kingdom, Denmar...","October 19, 2020",2005,TV-MA,99 min,When Lebanon's Civil War deprives Zozo of his ...
7783,s7784,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,A scrappy but poor boy worms his way into a ty...
7784,s7785,Movie,Zulu Man in Japan,NaN,Nasty C,NaN,"September 25, 2020",2019,TV-MA,44 min,"In this documentary, South African rapper Nast..."
7785,s7786,TV Show,Zumbo's Just Desserts,NaN,"Adriano Zumbo, Rachel Khoo",Australia,"October 31, 2020",2019,TV-PG,1 Season,Dessert wizard Adriano Zumbo looks for the nex...
7786,s7787,Movie,ZZ TOP: THAT LITTLE OL' BAND FROM TEXAS,Sam Dunn,NaN,"United Kingdom, Canada, United States","March 1, 2020",2019,TV-MA,90 min,This documentary delves into the mystique behi...

In [31]:
netflix.dropna(subset = ['director']) # drop observaciones que presentan missing values en la columna director

netflix.dropna(subset = ['director']) 

 # Reemplazar missing values de la columna director con la palabra "Sin director"
# netflix.director = netflix.director.fillna("Sin director")

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
1,s2,Movie,7:19,Jorge Michel Grau,"Demián Bichir, Héctor Bonilla, Oscar Serrano, ...",Mexico,"December 23, 2016",2016,TV-MA,93 min,"Dramas, International Movies",After a devastating earthquake hits Mexico Cit...
2,s3,Movie,23:59,Gilbert Chan,"Tedd Chan, Stella Chung, Henley Hii, Lawrence ...",Singapore,"December 20, 2018",2011,R,78 min,"Horror Movies, International Movies","When an army recruit is found dead, his fellow..."
3,s4,Movie,9,Shane Acker,"Elijah Wood, John C. Reilly, Jennifer Connelly...",United States,"November 16, 2017",2009,PG-13,80 min,"Action & Adventure, Independent Movies, Sci-Fi...","In a postapocalyptic world, rag-doll robots hi..."
4,s5,Movie,21,Robert Luketic,"Jim Sturgess, Kevin Spacey, Kate Bosworth, Aar...",United States,"January 1, 2020",2008,PG-13,123 min,Dramas,A brilliant group of students become card-coun...
5,s6,TV Show,46,Serdar Akar,"Erdal Beşikçioğlu, Yasemin Allen, Melis Birkan...",Turkey,"July 1, 2017",2016,TV-MA,1 Season,"International TV Shows, TV Dramas, TV Mysteries",A genetics professor experiments with a treatm...
...,...,...,...,...,...,...,...,...,...,...,...,...
7780,s7781,Movie,Zoo,Shlok Sharma,"Shashank Arora, Shweta Tripathi, Rahul Kumar, ...",India,"July 1, 2018",2018,TV-MA,94 min,"Dramas, Independent Movies, International Movies",A drug dealer starts having doubts about his t...
7781,s7782,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
7782,s7783,Movie,Zozo,Josef Fares,"Imad Creidi, Antoinette Turk, Elias Gergi, Car...","Sweden, Czech Republic, United Kingdom, Denmar...","October 19, 2020",2005,TV-MA,99 min,"Dramas, International Movies",When Lebanon's Civil War deprives Zozo of his ...
7783,s7784,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...
7786,s7787,Movie,ZZ TOP: THAT LITTLE OL' BAND FROM TEXAS,Sam Dunn,NaN,"United Kingdom, Canada, United States","March 1, 2020",2019,TV-MA,90 min,"Documentaries, Music & Musicals",This documentary delves into the mystique behi...

In [56]:
# netflix['director'] = netflix.director.fillna("Sin director")

In [34]:
netflix.director.fillna("Sin director")

netflix

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,TV Show,3%,NaN,"João Miguel, Bianca Comparato, Michel Gomes, R...",Brazil,"August 14, 2020",2020,TV-MA,4 Seasons,"International TV Shows, TV Dramas, TV Sci-Fi &...",In a future where the elite inhabit an island ...
1,s2,Movie,7:19,Jorge Michel Grau,"Demián Bichir, Héctor Bonilla, Oscar Serrano, ...",Mexico,"December 23, 2016",2016,TV-MA,93 min,"Dramas, International Movies",After a devastating earthquake hits Mexico Cit...
2,s3,Movie,23:59,Gilbert Chan,"Tedd Chan, Stella Chung, Henley Hii, Lawrence ...",Singapore,"December 20, 2018",2011,R,78 min,"Horror Movies, International Movies","When an army recruit is found dead, his fellow..."
3,s4,Movie,9,Shane Acker,"Elijah Wood, John C. Reilly, Jennifer Connelly...",United States,"November 16, 2017",2009,PG-13,80 min,"Action & Adventure, Independent Movies, Sci-Fi...","In a postapocalyptic world, rag-doll robots hi..."
4,s5,Movie,21,Robert Luketic,"Jim Sturgess, Kevin Spacey, Kate Bosworth, Aar...",United States,"January 1, 2020",2008,PG-13,123 min,Dramas,A brilliant group of students become card-coun...
...,...,...,...,...,...,...,...,...,...,...,...,...
7782,s7783,Movie,Zozo,Josef Fares,"Imad Creidi, Antoinette Turk, Elias Gergi, Car...","Sweden, Czech Republic, United Kingdom, Denmar...","October 19, 2020",2005,TV-MA,99 min,"Dramas, International Movies",When Lebanon's Civil War deprives Zozo of his ...
7783,s7784,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...
7784,s7785,Movie,Zulu Man in Japan,NaN,Nasty C,NaN,"September 25, 2020",2019,TV-MA,44 min,"Documentaries, International Movies, Music & M...","In this documentary, South African rapper Nast..."
7785,s7786,TV Show,Zumbo's Just Desserts,NaN,"Adriano Zumbo, Rachel Khoo",Australia,"October 31, 2020",2019,TV-PG,1 Season,"International TV Shows, Reality TV",Dessert wizard Adriano Zumbo looks for the nex...
7786,s7787,Movie,ZZ TOP: THAT LITTLE OL' BAND FROM TEXAS,Sam Dunn,NaN,"United Kingdom, Canada, United States","March 1, 2020",2019,TV-MA,90 min,"Documentaries, Music & Musicals",This documentary delves into the mystique behi...

In [35]:
# Alrerar la misma base de datos sin la necesidad de asignar a uno nuevo 

netflix.director.fillna("Sin director", inplace = True)


# Qué funciones admiten Inplace = True

# drop, fillna, rename

In [36]:
netflix

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,TV Show,3%,Sin director,"João Miguel, Bianca Comparato, Michel Gomes, R...",Brazil,"August 14, 2020",2020,TV-MA,4 Seasons,"International TV Shows, TV Dramas, TV Sci-Fi &...",In a future where the elite inhabit an island ...
1,s2,Movie,7:19,Jorge Michel Grau,"Demián Bichir, Héctor Bonilla, Oscar Serrano, ...",Mexico,"December 23, 2016",2016,TV-MA,93 min,"Dramas, International Movies",After a devastating earthquake hits Mexico Cit...
2,s3,Movie,23:59,Gilbert Chan,"Tedd Chan, Stella Chung, Henley Hii, Lawrence ...",Singapore,"December 20, 2018",2011,R,78 min,"Horror Movies, International Movies","When an army recruit is found dead, his fellow..."
3,s4,Movie,9,Shane Acker,"Elijah Wood, John C. Reilly, Jennifer Connelly...",United States,"November 16, 2017",2009,PG-13,80 min,"Action & Adventure, Independent Movies, Sci-Fi...","In a postapocalyptic world, rag-doll robots hi..."
4,s5,Movie,21,Robert Luketic,"Jim Sturgess, Kevin Spacey, Kate Bosworth, Aar...",United States,"January 1, 2020",2008,PG-13,123 min,Dramas,A brilliant group of students become card-coun...
...,...,...,...,...,...,...,...,...,...,...,...,...
7782,s7783,Movie,Zozo,Josef Fares,"Imad Creidi, Antoinette Turk, Elias Gergi, Car...","Sweden, Czech Republic, United Kingdom, Denmar...","October 19, 2020",2005,TV-MA,99 min,"Dramas, International Movies",When Lebanon's Civil War deprives Zozo of his ...
7783,s7784,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...
7784,s7785,Movie,Zulu Man in Japan,Sin director,Nasty C,NaN,"September 25, 2020",2019,TV-MA,44 min,"Documentaries, International Movies, Music & M...","In this documentary, South African rapper Nast..."
7785,s7786,TV Show,Zumbo's Just Desserts,Sin director,"Adriano Zumbo, Rachel Khoo",Australia,"October 31, 2020",2019,TV-PG,1 Season,"International TV Shows, Reality TV",Dessert wizard Adriano Zumbo looks for the nex...
7786,s7787,Movie,ZZ TOP: THAT LITTLE OL' BAND FROM TEXAS,Sam Dunn,NaN,"United Kingdom, Canada, United States","March 1, 2020",2019,TV-MA,90 min,"Documentaries, Music & Musicals",This documentary delves into the mystique behi...

- Notese que la base de datos Netflix no ha sido alterada. Para que la base de datos se altere debe ocurrir dos cosas:
1. Asignarse a una nueva base de datos 
2. Si la función lo permite, incluir el input ***Inplace = True***

In [37]:
# Create new variable
netflix['new_col'] = np.arange(0, netflix.shape[0]) # creat new varaible

In [38]:
netflix.loc[210:500]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,new_col
210,s211,Movie,A Night at the Roxbury,John Fortenberry,"Will Ferrell, Chris Kattan, Dan Hedaya, Molly ...",United States,"December 1, 2019",1998,PG-13,82 min,"Comedies, Cult Movies","After a run-in with Richard Grieco, dimwits Do...",210
211,s212,Movie,A Noble Intention,Joram Lürsen,"Gijs Scholten van Aschat, Jacob Derwig, Rifka ...",Netherlands,"September 1, 2016",2015,TV-MA,111 min,"Dramas, International Movies","In 1888 Amsterdam, a headstrong violin maker f...",211
212,s213,Movie,A Patch of Fog,Michael Lennox,"Stephen Graham, Conleth Hill, Lara Pulver, Ars...",United Kingdom,"April 15, 2017",2015,TV-MA,92 min,"Dramas, Thrillers",When a guard catches a writer-television host ...,212
213,s214,TV Show,A Perfect Crime,Sin director,NaN,Germany,"September 25, 2020",2020,TV-14,1 Season,"Crime TV Shows, Docuseries, International TV S...",This docuseries investigates the 1991 killing ...,213
214,s215,Movie,A Perfect Ending,Nicole Conn,"Barbara Niven, Jessica Clark, John Heard, Morg...",United States,"January 1, 2019",2012,TV-MA,110 min,"Dramas, Independent Movies, LGBTQ Movies","After confessing an unusual secret, a represse...",214
...,...,...,...,...,...,...,...,...,...,...,...,...,...
496,s497,Movie,An Ordinary Man,Brad Silberling,"Ben Kingsley, Hera Hilmar, Peter Serafinowicz","Serbia, United States","October 1, 2020",2017,R,91 min,"Dramas, Thrillers",A war criminal in hiding begins to suspect tha...,496
497,s498,Movie,An Unremarkable Christmas,Juan Camilo Pinzon,"Antonio Sanint, Luis Eduardo Arango, María Cec...",Colombia,"December 17, 2020",2020,TV-14,83 min,"Comedies, Dramas, International Movies",An accountant and aspiring magician invites hi...,497
498,s499,Movie,An Upper Egyptian,"Ismail Farouk, Hazem Fouda","Mohamed Ramadan, Randa El Behery, Nermin Maher...",Egypt,"June 20, 2019",2014,TV-MA,85 min,"Comedies, Dramas, International Movies","Eager to settle down, Abdullah searches for th...",498
499,s500,Movie,Ana e Vitória,Matheus Souza,"Ana Caetano, Vitória Falcão, Clarissa Müller, ...",Brazil,"November 2, 2018",2018,TV-MA,116 min,"Comedies, International Movies, LGBTQ Movies","After meeting by chance, two young musicians w...",499
500,s501,Movie,Anaamika,Sekhar Kammula,"Nayantara, Vaibhav Reddy, Pasupathy, Harshvard...",India,"September 17, 2020",2014,TV-14,130 min,"International Movies, Thrillers",As a woman scours Hyderabad for her missing hu...,500

In [45]:
'''
Loc usa los nombres de filas y columnas para filtrar
'''

# Filter rows

netflix.loc[0:100]
netflix.loc[210:500]
netflix.loc[210:] # desde la fila posición 210 hasta al final 

# filter columns 

netflix.loc[:,['show_id','type','description']]

netflix.loc[1000:2000,['show_id','type','description']]

     show_id     type                                        description
1000   s1001  TV Show  This sequel to the award-winning nature series...
1001   s1002    Movie  Bad news from the past unhinges vagabond Dwigh...
1002   s1003    Movie  A jewel thief returns to his hiding place afte...
1003   s1004    Movie  As Cindy and Dean muddle through their languis...
1004   s1005    Movie  When his girlfriend learns the truth about his...
...      ...      ...                                                ...
1996   s1997    Movie  This documentary explores the extent to which ...
1997   s1998    Movie  Warehouse workers Vince and Zack compete in a ...
1998   s1999  TV Show  This fictional series tells the stories of wha...
1999   s2000    Movie  After accidentally killing a young mobster, a ...
2000   s2001  TV Show  This documentary series tries to get at the ro...

[1001 rows x 3 columns]

In [44]:
netflix[['show_id','type','description']]

     show_id     type                                        description
0         s1  TV Show  In a future where the elite inhabit an island ...
1         s2    Movie  After a devastating earthquake hits Mexico Cit...
2         s3    Movie  When an army recruit is found dead, his fellow...
3         s4    Movie  In a postapocalyptic world, rag-doll robots hi...
4         s5    Movie  A brilliant group of students become card-coun...
...      ...      ...                                                ...
7782   s7783    Movie  When Lebanon's Civil War deprives Zozo of his ...
7783   s7784    Movie  A scrappy but poor boy worms his way into a ty...
7784   s7785    Movie  In this documentary, South African rapper Nast...
7785   s7786  TV Show  Dessert wizard Adriano Zumbo looks for the nex...
7786   s7787    Movie  This documentary delves into the mystique behi...

[7787 rows x 3 columns]

In [46]:
netflix.set_index( [ 'show_id' ] , inplace = True)
netflix.head()

,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,new_col
show_id,,,,,,,,,,,,
s1,TV Show,3%,Sin director,"João Miguel, Bianca Comparato, Michel Gomes, R...",Brazil,"August 14, 2020",2020,TV-MA,4 Seasons,"International TV Shows, TV Dramas, TV Sci-Fi &...",In a future where the elite inhabit an island ...,0
s2,Movie,7:19,Jorge Michel Grau,"Demián Bichir, Héctor Bonilla, Oscar Serrano, ...",Mexico,"December 23, 2016",2016,TV-MA,93 min,"Dramas, International Movies",After a devastating earthquake hits Mexico Cit...,1
s3,Movie,23:59,Gilbert Chan,"Tedd Chan, Stella Chung, Henley Hii, Lawrence ...",Singapore,"December 20, 2018",2011,R,78 min,"Horror Movies, International Movies","When an army recruit is found dead, his fellow...",2
s4,Movie,9,Shane Acker,"Elijah Wood, John C. Reilly, Jennifer Connelly...",United States,"November 16, 2017",2009,PG-13,80 min,"Action & Adventure, Independent Movies, Sci-Fi...","In a postapocalyptic world, rag-doll robots hi...",3
s5,Movie,21,Robert Luketic,"Jim Sturgess, Kevin Spacey, Kate Bosworth, Aar...",United States,"January 1, 2020",2008,PG-13,123 min,Dramas,A brilliant group of students become card-coun...,4

In [48]:
# Filtrando columnas por index

netflix.loc[['s1','s100','s7000']]

,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,new_col
show_id,,,,,,,,,,,,
s1,TV Show,3%,Sin director,"João Miguel, Bianca Comparato, Michel Gomes, R...",Brazil,"August 14, 2020",2020,TV-MA,4 Seasons,"International TV Shows, TV Dramas, TV Sci-Fi &...",In a future where the elite inhabit an island ...,0
s100,Movie,3 Heroines,Iman Brotoseno,"Reza Rahadian, Bunga Citra Lestari, Tara Basro...",Indonesia,"January 5, 2019",2016,TV-PG,124 min,"Dramas, International Movies, Sports Movies",Three Indonesian women break records by becomi...,99
s7000,TV Show,The Wiggles,Sin director,"Anthony Field, Lachlan Gillespie, Simon Pryce,...",Australia,"May 15, 2020",2015,TV-Y,2 Seasons,Kids' TV,"The top band for preschool kids, The Wiggles, ...",6999

In [49]:
# Reset index 

netflix.reset_index( inplace = True)

In [50]:
netflix

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,new_col
0,s1,TV Show,3%,Sin director,"João Miguel, Bianca Comparato, Michel Gomes, R...",Brazil,"August 14, 2020",2020,TV-MA,4 Seasons,"International TV Shows, TV Dramas, TV Sci-Fi &...",In a future where the elite inhabit an island ...,0
1,s2,Movie,7:19,Jorge Michel Grau,"Demián Bichir, Héctor Bonilla, Oscar Serrano, ...",Mexico,"December 23, 2016",2016,TV-MA,93 min,"Dramas, International Movies",After a devastating earthquake hits Mexico Cit...,1
2,s3,Movie,23:59,Gilbert Chan,"Tedd Chan, Stella Chung, Henley Hii, Lawrence ...",Singapore,"December 20, 2018",2011,R,78 min,"Horror Movies, International Movies","When an army recruit is found dead, his fellow...",2
3,s4,Movie,9,Shane Acker,"Elijah Wood, John C. Reilly, Jennifer Connelly...",United States,"November 16, 2017",2009,PG-13,80 min,"Action & Adventure, Independent Movies, Sci-Fi...","In a postapocalyptic world, rag-doll robots hi...",3
4,s5,Movie,21,Robert Luketic,"Jim Sturgess, Kevin Spacey, Kate Bosworth, Aar...",United States,"January 1, 2020",2008,PG-13,123 min,Dramas,A brilliant group of students become card-coun...,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...
7782,s7783,Movie,Zozo,Josef Fares,"Imad Creidi, Antoinette Turk, Elias Gergi, Car...","Sweden, Czech Republic, United Kingdom, Denmar...","October 19, 2020",2005,TV-MA,99 min,"Dramas, International Movies",When Lebanon's Civil War deprives Zozo of his ...,7782
7783,s7784,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...,7783
7784,s7785,Movie,Zulu Man in Japan,Sin director,Nasty C,NaN,"September 25, 2020",2019,TV-MA,44 min,"Documentaries, International Movies, Music & M...","In this documentary, South African rapper Nast...",7784
7785,s7786,TV Show,Zumbo's Just Desserts,Sin director,"Adriano Zumbo, Rachel Khoo",Australia,"October 31, 2020",2019,TV-PG,1 Season,"International TV Shows, Reality TV",Dessert wizard Adriano Zumbo looks for the nex...,7785
7786,s7787,Movie,ZZ TOP: THAT LITTLE OL' BAND FROM TEXAS,Sam Dunn,NaN,"United Kingdom, Canada, United States","March 1, 2020",2019,TV-MA,90 min,"Documentaries, Music & Musicals",This documentary delves into the mystique behi...,7786

In [51]:
'''
iloc usa las posiciones de filas y columnas
'''

# Filter rows

netflix.iloc[0:100]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,new_col
0,s1,TV Show,3%,Sin director,"João Miguel, Bianca Comparato, Michel Gomes, R...",Brazil,"August 14, 2020",2020,TV-MA,4 Seasons,"International TV Shows, TV Dramas, TV Sci-Fi &...",In a future where the elite inhabit an island ...,0
1,s2,Movie,7:19,Jorge Michel Grau,"Demián Bichir, Héctor Bonilla, Oscar Serrano, ...",Mexico,"December 23, 2016",2016,TV-MA,93 min,"Dramas, International Movies",After a devastating earthquake hits Mexico Cit...,1
2,s3,Movie,23:59,Gilbert Chan,"Tedd Chan, Stella Chung, Henley Hii, Lawrence ...",Singapore,"December 20, 2018",2011,R,78 min,"Horror Movies, International Movies","When an army recruit is found dead, his fellow...",2
3,s4,Movie,9,Shane Acker,"Elijah Wood, John C. Reilly, Jennifer Connelly...",United States,"November 16, 2017",2009,PG-13,80 min,"Action & Adventure, Independent Movies, Sci-Fi...","In a postapocalyptic world, rag-doll robots hi...",3
4,s5,Movie,21,Robert Luketic,"Jim Sturgess, Kevin Spacey, Kate Bosworth, Aar...",United States,"January 1, 2020",2008,PG-13,123 min,Dramas,A brilliant group of students become card-coun...,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,s96,TV Show,28 Moons,Sin director,"Jin-sung Yang, Kyu-jong Kim, Tae-hwan Kang, Ge...",South Korea,"June 10, 2017",2016,TV-PG,1 Season,"International TV Shows, Korean TV Shows, Roman...",When her fiancé acts strangely upon receiving ...,95
96,s97,Movie,3 Days to Kill,McG,"Kevin Costner, Amber Heard, Hailee Steinfeld, ...","United States, France, Serbia","December 1, 2020",2014,PG-13,117 min,Action & Adventure,A terminally ill secret agent accepts a risky ...,96
97,s98,Movie,3 Deewarein,Nagesh Kukunoor,"Naseeruddin Shah, Jackie Shroff, Juhi Chawla, ...",NaN,"December 31, 2019",2003,TV-MA,121 min,"Dramas, International Movies, Thrillers",A reporter interviews three convicts on death ...,97
98,s99,Movie,3 Generations,Gaby Dellal,"Elle Fanning, Naomi Watts, Susan Sarandon, Tat...",United States,"August 28, 2017",2015,PG-13,92 min,"Dramas, LGBTQ Movies",When teenage Ray begins transitioning from fem...,98
99,s100,Movie,3 Heroines,Iman Brotoseno,"Reza Rahadian, Bunga Citra Lestari, Tara Basro...",Indonesia,"January 5, 2019",2016,TV-PG,124 min,"Dramas, International Movies, Sports Movies",Three Indonesian women break records by becomi...,99

In [52]:
netflix.iloc[210:500]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,new_col
210,s211,Movie,A Night at the Roxbury,John Fortenberry,"Will Ferrell, Chris Kattan, Dan Hedaya, Molly ...",United States,"December 1, 2019",1998,PG-13,82 min,"Comedies, Cult Movies","After a run-in with Richard Grieco, dimwits Do...",210
211,s212,Movie,A Noble Intention,Joram Lürsen,"Gijs Scholten van Aschat, Jacob Derwig, Rifka ...",Netherlands,"September 1, 2016",2015,TV-MA,111 min,"Dramas, International Movies","In 1888 Amsterdam, a headstrong violin maker f...",211
212,s213,Movie,A Patch of Fog,Michael Lennox,"Stephen Graham, Conleth Hill, Lara Pulver, Ars...",United Kingdom,"April 15, 2017",2015,TV-MA,92 min,"Dramas, Thrillers",When a guard catches a writer-television host ...,212
213,s214,TV Show,A Perfect Crime,Sin director,NaN,Germany,"September 25, 2020",2020,TV-14,1 Season,"Crime TV Shows, Docuseries, International TV S...",This docuseries investigates the 1991 killing ...,213
214,s215,Movie,A Perfect Ending,Nicole Conn,"Barbara Niven, Jessica Clark, John Heard, Morg...",United States,"January 1, 2019",2012,TV-MA,110 min,"Dramas, Independent Movies, LGBTQ Movies","After confessing an unusual secret, a represse...",214
...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,s496,Movie,An Interview with God,Perry Lang,"Brenton Thwaites, David Strathairn, Hill Harpe...",United States,"March 1, 2019",2018,TV-PG,97 min,"Dramas, Faith & Spirituality","After an assignment in a war zone, a journalis...",495
496,s497,Movie,An Ordinary Man,Brad Silberling,"Ben Kingsley, Hera Hilmar, Peter Serafinowicz","Serbia, United States","October 1, 2020",2017,R,91 min,"Dramas, Thrillers",A war criminal in hiding begins to suspect tha...,496
497,s498,Movie,An Unremarkable Christmas,Juan Camilo Pinzon,"Antonio Sanint, Luis Eduardo Arango, María Cec...",Colombia,"December 17, 2020",2020,TV-14,83 min,"Comedies, Dramas, International Movies",An accountant and aspiring magician invites hi...,497
498,s499,Movie,An Upper Egyptian,"Ismail Farouk, Hazem Fouda","Mohamed Ramadan, Randa El Behery, Nermin Maher...",Egypt,"June 20, 2019",2014,TV-MA,85 min,"Comedies, Dramas, International Movies","Eager to settle down, Abdullah searches for th...",498
499,s500,Movie,Ana e Vitória,Matheus Souza,"Ana Caetano, Vitória Falcão, Clarissa Müller, ...",Brazil,"November 2, 2018",2018,TV-MA,116 min,"Comedies, International Movies, LGBTQ Movies","After meeting by chance, two young musicians w...",499

In [54]:
# filter columns 

netflix.iloc[:,[0,1,12]]

     show_id     type  new_col
0         s1  TV Show        0
1         s2    Movie        1
2         s3    Movie        2
3         s4    Movie        3
4         s5    Movie        4
...      ...      ...      ...
7782   s7783    Movie     7782
7783   s7784    Movie     7783
7784   s7785    Movie     7784
7785   s7786  TV Show     7785
7786   s7787    Movie     7786

[7787 rows x 3 columns]

In [55]:
netflix.iloc[1000:2000,[0,1,12]]

     show_id     type  new_col
1000   s1001  TV Show     1000
1001   s1002    Movie     1001
1002   s1003    Movie     1002
1003   s1004    Movie     1003
1004   s1005    Movie     1004
...      ...      ...      ...
1995   s1996  TV Show     1995
1996   s1997    Movie     1996
1997   s1998    Movie     1997
1998   s1999  TV Show     1998
1999   s2000    Movie     1999

[1000 rows x 3 columns]

In [56]:
# Column names in a list
list(netflix.columns)

['show_id',
 'type',
 'title',
 'director',
 'cast',
 'country',
 'date_added',
 'release_year',
 'rating',
 'duration',
 'listed_in',
 'description',
 'new_col']

### ***Sorting and Subsetting***

In [59]:
# sort ascendet 
netflix.sort_values("release_year", inplace = True)
netflix

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,new_col
4867,s4868,TV Show,Pioneers: First Women Filmmakers*,Sin director,NaN,NaN,"December 30, 2018",1925,TV-14,1 Season,TV Shows,This collection restores films from women who ...,4867
6117,s6118,Movie,The Battle of Midway,John Ford,"Henry Fonda, Jane Darwell",United States,"March 31, 2017",1942,TV-14,18 min,"Classic Movies, Documentaries",Director John Ford captures combat footage of ...,6117
4960,s4961,Movie,Prelude to War,Frank Capra,NaN,United States,"March 31, 2017",1942,TV-14,52 min,"Classic Movies, Documentaries",Frank Capra's documentary chronicles the rise ...,4960
7679,s7680,Movie,WWII: Report from the Aleutians,John Huston,NaN,United States,"March 31, 2017",1943,TV-PG,45 min,Documentaries,Filmmaker John Huston narrates this Oscar-nomi...,7679
7342,s7343,Movie,Undercover: How to Operate Behind Enemy Lines,John Ford,NaN,United States,"March 31, 2017",1943,TV-PG,61 min,"Classic Movies, Documentaries",This World War II-era training film dramatizes...,7342
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1864,s1865,TV Show,Dream Home Makeover,Sin director,NaN,United States,"January 1, 2021",2021,TV-G,2 Seasons,Reality TV,Dreams come true for real families looking for...,1864
6477,s6478,TV Show,The Idhun Chronicles,Maite Ruiz De Austri,"Michelle Jenner, Itzan Escamilla, Sergio Mur, ...",Spain,"January 8, 2021",2021,TV-14,2 Seasons,"Anime Series, International TV Shows, Spanish-...",A boy suddenly orphaned fights his parents' ki...,6477
2672,s2673,TV Show,Headspace Guide to Meditation,Sin director,Andy Puddicombe,United States,"January 1, 2021",2021,TV-G,1 Season,"Docuseries, Science & Nature TV","Headspace takes a friendly, animated look at t...",2672
6670,s6671,Movie,The Minimalists: Less Is Now,Sin director,NaN,United States,"January 1, 2021",2021,TV-14,54 min,Documentaries,They've built a movement out of minimalism. Lo...,6670
4468,s4469,TV Show,Night Stalker: The Hunt for a Serial Killer,Tiller Russell,NaN,NaN,"January 13, 2021",2021,TV-MA,1 Season,"Crime TV Shows, Docuseries",Beneath the sunlit glamour of 1985 LA lurks a ...,4468

In [61]:
net_new = netflix.sort_values("release_year", ascending = False)
net_new.head(10)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,new_col
4468,s4469,TV Show,Night Stalker: The Hunt for a Serial Killer,Tiller Russell,NaN,NaN,"January 13, 2021",2021,TV-MA,1 Season,"Crime TV Shows, Docuseries",Beneath the sunlit glamour of 1985 LA lurks a ...,4468
4710,s4711,Movie,Outside the Wire,Mikael Håfström,"Anthony Mackie, Damson Idris, Emily Beecham, M...",NaN,"January 15, 2021",2021,R,116 min,Action & Adventure,"In the near future, a drone pilot sent into a ...",4710
5103,s5104,Movie,Ratones Paranoicos: The Band that Rocked Argen...,"Alejandro Ruax, Ramiro Martínez","Juan Sebastián Gutiérrez, Pablo Cano, Pablo Me...",NaN,"January 6, 2021",2021,TV-MA,76 min,"Documentaries, International Movies, Music & M...","The irrepressible Ratones Paranoicos, Argentin...",5103
1780,s1781,TV Show,Disenchantment,Sin director,"Abbi Jacobson, Eric André, Nat Faxon, John DiM...",United States,"January 15, 2021",2021,TV-14,3 Seasons,"TV Action & Adventure, TV Comedies, TV Sci-Fi ...","Princess duties call, but she'd rather be drin...",1780
7569,s7570,Movie,What Would Sophia Loren Do?,Ross Kauffman,"Nancy ""Vincenza Careri"" Kulik, Sophia Loren",United States,"January 15, 2021",2021,TV-14,32 min,Documentaries,"In this delightful short documentary, an Itali...",7569
1528,s1529,Movie,Creating The Queen's Gambit,Sin director,NaN,NaN,"January 8, 2021",2021,TV-14,14 min,Documentaries,A fascinating character. Exquisite sets. A wig...,1528
7220,s7221,Movie,Tribhanga - Tedhi Medhi Crazy,Renuka Shahane,"Kajol, Tanvi Azmi, Mithila Palkar, Kunaal Roy ...",NaN,"January 15, 2021",2021,TV-MA,96 min,"Dramas, International Movies","When her estranged mother falls into a coma, a...",7220
4965,s4966,TV Show,Pretend It’s a City,Sin director,Fran Lebowitz,United States,"January 8, 2021",2021,TV-14,1 Season,Docuseries,Wander the New York City streets and fascinati...,4965
3018,s3019,TV Show,Inside the World’s Toughest Prisons,Sin director,Paul Connolly,United Kingdom,"January 8, 2021",2021,TV-MA,5 Seasons,"British TV Shows, Crime TV Shows, Docuseries",Investigative journalist Paul Connolly becomes...,3018
7644,s7645,Movie,Wish You,Sung Do-jun,"Kang In-soo, Lee Sang, Soo-bin",NaN,"January 15, 2021",2021,TV-PG,102 min,"Dramas, International Movies, LGBTQ Movies","Singing and dreaming together, a talented sing...",7644

In [62]:
netflix['number'] = np.random.randint(1, 10, netflix.shape[0])

In [64]:
netflix.sort_values(["release_year","number"], inplace = True)
netflix.head(10)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,new_col,number
4867,s4868,TV Show,Pioneers: First Women Filmmakers*,Sin director,NaN,NaN,"December 30, 2018",1925,TV-14,1 Season,TV Shows,This collection restores films from women who ...,4867,4
4960,s4961,Movie,Prelude to War,Frank Capra,NaN,United States,"March 31, 2017",1942,TV-14,52 min,"Classic Movies, Documentaries",Frank Capra's documentary chronicles the rise ...,4960,7
6117,s6118,Movie,The Battle of Midway,John Ford,"Henry Fonda, Jane Darwell",United States,"March 31, 2017",1942,TV-14,18 min,"Classic Movies, Documentaries",Director John Ford captures combat footage of ...,6117,8
7616,s7617,Movie,Why We Fight: The Battle of Russia,"Frank Capra, Anatole Litvak",NaN,United States,"March 31, 2017",1943,TV-PG,82 min,Documentaries,This installment of Frank Capra's acclaimed do...,7616,2
7342,s7343,Movie,Undercover: How to Operate Behind Enemy Lines,John Ford,NaN,United States,"March 31, 2017",1943,TV-PG,61 min,"Classic Movies, Documentaries",This World War II-era training film dramatizes...,7342,4
7679,s7680,Movie,WWII: Report from the Aleutians,John Huston,NaN,United States,"March 31, 2017",1943,TV-PG,45 min,Documentaries,Filmmaker John Huston narrates this Oscar-nomi...,7679,8
6657,s6658,Movie,The Memphis Belle: A Story of a\r\nFlying Fort...,William Wyler,NaN,United States,"March 31, 2017",1944,TV-PG,40 min,"Classic Movies, Documentaries",This documentary centers on the crew of the B-...,6657,3
6699,s6700,Movie,The Negro Soldier,Stuart Heisler,NaN,United States,"March 31, 2017",1944,TV-14,40 min,"Classic Movies, Documentaries",This documentary urged African Americans to en...,6699,4
7268,s7269,Movie,Tunisian Victory,"Frank Capra, John Huston, Hugh Stewart, Roy Bo...",Burgess Meredith,"United States, United Kingdom","March 31, 2017",1944,TV-14,76 min,"Classic Movies, Documentaries",British and American troops join forces to lib...,7268,5
3425,s3426,Movie,Know Your Enemy - Japan,"Frank Capra, Joris Ivens","Walter Huston, Dana Andrews",United States,"March 31, 2017",1945,TV-14,63 min,"Classic Movies, Documentaries",Though culturally insensitive by modern standa...,3425,1

In [65]:
net_two_sort = netflix.sort_values(["release_year","number"], ascending = [True,False]) 
net_two_sort.head(10)
# obs : en 1943 ==> en ["duration"] lo ordena de forma descendente

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,new_col,number
4867,s4868,TV Show,Pioneers: First Women Filmmakers*,Sin director,NaN,NaN,"December 30, 2018",1925,TV-14,1 Season,TV Shows,This collection restores films from women who ...,4867,4
6117,s6118,Movie,The Battle of Midway,John Ford,"Henry Fonda, Jane Darwell",United States,"March 31, 2017",1942,TV-14,18 min,"Classic Movies, Documentaries",Director John Ford captures combat footage of ...,6117,8
4960,s4961,Movie,Prelude to War,Frank Capra,NaN,United States,"March 31, 2017",1942,TV-14,52 min,"Classic Movies, Documentaries",Frank Capra's documentary chronicles the rise ...,4960,7
7679,s7680,Movie,WWII: Report from the Aleutians,John Huston,NaN,United States,"March 31, 2017",1943,TV-PG,45 min,Documentaries,Filmmaker John Huston narrates this Oscar-nomi...,7679,8
7342,s7343,Movie,Undercover: How to Operate Behind Enemy Lines,John Ford,NaN,United States,"March 31, 2017",1943,TV-PG,61 min,"Classic Movies, Documentaries",This World War II-era training film dramatizes...,7342,4
7616,s7617,Movie,Why We Fight: The Battle of Russia,"Frank Capra, Anatole Litvak",NaN,United States,"March 31, 2017",1943,TV-PG,82 min,Documentaries,This installment of Frank Capra's acclaimed do...,7616,2
7268,s7269,Movie,Tunisian Victory,"Frank Capra, John Huston, Hugh Stewart, Roy Bo...",Burgess Meredith,"United States, United Kingdom","March 31, 2017",1944,TV-14,76 min,"Classic Movies, Documentaries",British and American troops join forces to lib...,7268,5
6699,s6700,Movie,The Negro Soldier,Stuart Heisler,NaN,United States,"March 31, 2017",1944,TV-14,40 min,"Classic Movies, Documentaries",This documentary urged African Americans to en...,6699,4
6657,s6658,Movie,The Memphis Belle: A Story of a\r\nFlying Fort...,William Wyler,NaN,United States,"March 31, 2017",1944,TV-PG,40 min,"Classic Movies, Documentaries",This documentary centers on the crew of the B-...,6657,3
5371,s5372,Movie,San Pietro,John Huston,NaN,United States,"March 31, 2017",1945,TV-14,32 min,"Classic Movies, Documentaries","After the Allies invade Italy, the Liri Valley...",5371,6

### ***Subsetting columns***

In [29]:
netflix.director

0            Sin director
1       Jorge Michel Grau
2            Gilbert Chan
3             Shane Acker
4          Robert Luketic
              ...
7782          Josef Fares
7783          Mozez Singh
7784         Sin director
7785         Sin director
7786             Sam Dunn
Name: director, Length: 7787, dtype: object

In [30]:
netflix[["director","cast"]]

               director                                               cast
0          Sin director  João Miguel, Bianca Comparato, Michel Gomes, R...
1     Jorge Michel Grau  Demián Bichir, Héctor Bonilla, Oscar Serrano, ...
2          Gilbert Chan  Tedd Chan, Stella Chung, Henley Hii, Lawrence ...
3           Shane Acker  Elijah Wood, John C. Reilly, Jennifer Connelly...
4        Robert Luketic  Jim Sturgess, Kevin Spacey, Kate Bosworth, Aar...
...                 ...                                                ...
7782        Josef Fares  Imad Creidi, Antoinette Turk, Elias Gergi, Car...
7783        Mozez Singh  Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...
7784       Sin director                                            Nasty C
7785       Sin director                         Adriano Zumbo, Rachel Khoo
7786           Sam Dunn                                                NaN

[7787 rows x 2 columns]

### ***Subsetting rows***

In [66]:
netflix[netflix["release_year"] < 2011].head(10)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,new_col,number
4867,s4868,TV Show,Pioneers: First Women Filmmakers*,Sin director,NaN,NaN,"December 30, 2018",1925,TV-14,1 Season,TV Shows,This collection restores films from women who ...,4867,4
4960,s4961,Movie,Prelude to War,Frank Capra,NaN,United States,"March 31, 2017",1942,TV-14,52 min,"Classic Movies, Documentaries",Frank Capra's documentary chronicles the rise ...,4960,7
6117,s6118,Movie,The Battle of Midway,John Ford,"Henry Fonda, Jane Darwell",United States,"March 31, 2017",1942,TV-14,18 min,"Classic Movies, Documentaries",Director John Ford captures combat footage of ...,6117,8
7616,s7617,Movie,Why We Fight: The Battle of Russia,"Frank Capra, Anatole Litvak",NaN,United States,"March 31, 2017",1943,TV-PG,82 min,Documentaries,This installment of Frank Capra's acclaimed do...,7616,2
7342,s7343,Movie,Undercover: How to Operate Behind Enemy Lines,John Ford,NaN,United States,"March 31, 2017",1943,TV-PG,61 min,"Classic Movies, Documentaries",This World War II-era training film dramatizes...,7342,4
7679,s7680,Movie,WWII: Report from the Aleutians,John Huston,NaN,United States,"March 31, 2017",1943,TV-PG,45 min,Documentaries,Filmmaker John Huston narrates this Oscar-nomi...,7679,8
6657,s6658,Movie,The Memphis Belle: A Story of a\r\nFlying Fort...,William Wyler,NaN,United States,"March 31, 2017",1944,TV-PG,40 min,"Classic Movies, Documentaries",This documentary centers on the crew of the B-...,6657,3
6699,s6700,Movie,The Negro Soldier,Stuart Heisler,NaN,United States,"March 31, 2017",1944,TV-14,40 min,"Classic Movies, Documentaries",This documentary urged African Americans to en...,6699,4
7268,s7269,Movie,Tunisian Victory,"Frank Capra, John Huston, Hugh Stewart, Roy Bo...",Burgess Meredith,"United States, United Kingdom","March 31, 2017",1944,TV-14,76 min,"Classic Movies, Documentaries",British and American troops join forces to lib...,7268,5
3425,s3426,Movie,Know Your Enemy - Japan,"Frank Capra, Joris Ivens","Walter Huston, Dana Andrews",United States,"March 31, 2017",1945,TV-14,63 min,"Classic Movies, Documentaries",Though culturally insensitive by modern standa...,3425,1

In [67]:
netflix[(netflix["release_year"] < 2011) & (netflix["number"] > 5)]  # para más de un condicional colocar los casos en paréntesis

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,new_col,number
4960,s4961,Movie,Prelude to War,Frank Capra,NaN,United States,"March 31, 2017",1942,TV-14,52 min,"Classic Movies, Documentaries",Frank Capra's documentary chronicles the rise ...,4960,7
6117,s6118,Movie,The Battle of Midway,John Ford,"Henry Fonda, Jane Darwell",United States,"March 31, 2017",1942,TV-14,18 min,"Classic Movies, Documentaries",Director John Ford captures combat footage of ...,6117,8
7679,s7680,Movie,WWII: Report from the Aleutians,John Huston,NaN,United States,"March 31, 2017",1943,TV-PG,45 min,Documentaries,Filmmaker John Huston narrates this Oscar-nomi...,7679,8
5371,s5372,Movie,San Pietro,John Huston,NaN,United States,"March 31, 2017",1945,TV-14,32 min,"Classic Movies, Documentaries","After the Allies invade Italy, the Liri Valley...",5371,6
4436,s4437,Movie,Nazi Concentration Camps,George Stevens,NaN,United States,"March 31, 2017",1945,TV-MA,59 min,"Classic Movies, Documentaries",Shocking footage shows Nazi concentration camp...,4436,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
915,s916,Movie,Bill Burr: Let It Go,Shannon Hartman,Bill Burr,United States,"November 10, 2017",2010,NR,65 min,Stand-Up Comedy,The musings of comedian Bill Burr are let loos...,915,9
299,s300,Movie,Act of Vengeance,Mahsun Kırmızıgül,"Haluk Bilginer, Mahsun Kırmızıgül, Mustafa San...","Turkey, United States","September 29, 2018",2010,NR,112 min,"Action & Adventure, International Movies",Two Turkish agents are sent to New York City o...,299,9
6596,s6597,Movie,The Light of My Eyes,Sin director,NaN,NaN,"June 5, 2020",2010,TV-MA,96 min,"Dramas, International Movies, Romantic Movies",A composer hides his love for his formerly bli...,6596,9
4302,s4303,Movie,My Amnesia Girl,Cathy Garcia-Molina,"John Lloyd Cruz, Toni Gonzaga, Carlos Agassi, ...",Philippines,"November 19, 2020",2010,TV-14,105 min,"International Movies, Romantic Movies",Years after leaving his bride-to-be at the alt...,4302,9
7061,s7062,Movie,Thorne: Sleepyhead,Stephen Hopkins,"David Morrissey, Eddie Marsan, Aidan Gillen, O...","United Kingdom, Australia, Canada, United States","November 2, 2016",2010,NR,125 min,"Dramas, International Movies",Investigating a series of attacks on young wom...,7061,9

In [69]:
netflix[( netflix.release_year < 2011 ) & (netflix.number > 5)]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,new_col,number
4960,s4961,Movie,Prelude to War,Frank Capra,NaN,United States,"March 31, 2017",1942,TV-14,52 min,"Classic Movies, Documentaries",Frank Capra's documentary chronicles the rise ...,4960,7
6117,s6118,Movie,The Battle of Midway,John Ford,"Henry Fonda, Jane Darwell",United States,"March 31, 2017",1942,TV-14,18 min,"Classic Movies, Documentaries",Director John Ford captures combat footage of ...,6117,8
7679,s7680,Movie,WWII: Report from the Aleutians,John Huston,NaN,United States,"March 31, 2017",1943,TV-PG,45 min,Documentaries,Filmmaker John Huston narrates this Oscar-nomi...,7679,8
5371,s5372,Movie,San Pietro,John Huston,NaN,United States,"March 31, 2017",1945,TV-14,32 min,"Classic Movies, Documentaries","After the Allies invade Italy, the Liri Valley...",5371,6
4436,s4437,Movie,Nazi Concentration Camps,George Stevens,NaN,United States,"March 31, 2017",1945,TV-MA,59 min,"Classic Movies, Documentaries",Shocking footage shows Nazi concentration camp...,4436,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
915,s916,Movie,Bill Burr: Let It Go,Shannon Hartman,Bill Burr,United States,"November 10, 2017",2010,NR,65 min,Stand-Up Comedy,The musings of comedian Bill Burr are let loos...,915,9
299,s300,Movie,Act of Vengeance,Mahsun Kırmızıgül,"Haluk Bilginer, Mahsun Kırmızıgül, Mustafa San...","Turkey, United States","September 29, 2018",2010,NR,112 min,"Action & Adventure, International Movies",Two Turkish agents are sent to New York City o...,299,9
6596,s6597,Movie,The Light of My Eyes,Sin director,NaN,NaN,"June 5, 2020",2010,TV-MA,96 min,"Dramas, International Movies, Romantic Movies",A composer hides his love for his formerly bli...,6596,9
4302,s4303,Movie,My Amnesia Girl,Cathy Garcia-Molina,"John Lloyd Cruz, Toni Gonzaga, Carlos Agassi, ...",Philippines,"November 19, 2020",2010,TV-14,105 min,"International Movies, Romantic Movies",Years after leaving his bride-to-be at the alt...,4302,9
7061,s7062,Movie,Thorne: Sleepyhead,Stephen Hopkins,"David Morrissey, Eddie Marsan, Aidan Gillen, O...","United Kingdom, Australia, Canada, United States","November 2, 2016",2010,NR,125 min,"Dramas, International Movies",Investigating a series of attacks on young wom...,7061,9

In [73]:
netflix[['director']].iloc[0:10]

                                               director
4867                                       Sin director
4960                                        Frank Capra
6117                                          John Ford
7616                        Frank Capra, Anatole Litvak
7342                                          John Ford
7679                                        John Huston
6657                                      William Wyler
6699                                     Stuart Heisler
7268  Frank Capra, John Huston, Hugh Stewart, Roy Bo...
3425                           Frank Capra, Joris Ivens

In [71]:
netflix

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,new_col,number
4867,s4868,TV Show,Pioneers: First Women Filmmakers*,Sin director,NaN,NaN,"December 30, 2018",1925,TV-14,1 Season,TV Shows,This collection restores films from women who ...,4867,4
4960,s4961,Movie,Prelude to War,Frank Capra,NaN,United States,"March 31, 2017",1942,TV-14,52 min,"Classic Movies, Documentaries",Frank Capra's documentary chronicles the rise ...,4960,7
6117,s6118,Movie,The Battle of Midway,John Ford,"Henry Fonda, Jane Darwell",United States,"March 31, 2017",1942,TV-14,18 min,"Classic Movies, Documentaries",Director John Ford captures combat footage of ...,6117,8
7616,s7617,Movie,Why We Fight: The Battle of Russia,"Frank Capra, Anatole Litvak",NaN,United States,"March 31, 2017",1943,TV-PG,82 min,Documentaries,This installment of Frank Capra's acclaimed do...,7616,2
7342,s7343,Movie,Undercover: How to Operate Behind Enemy Lines,John Ford,NaN,United States,"March 31, 2017",1943,TV-PG,61 min,"Classic Movies, Documentaries",This World War II-era training film dramatizes...,7342,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1864,s1865,TV Show,Dream Home Makeover,Sin director,NaN,United States,"January 1, 2021",2021,TV-G,2 Seasons,Reality TV,Dreams come true for real families looking for...,1864,7
4468,s4469,TV Show,Night Stalker: The Hunt for a Serial Killer,Tiller Russell,NaN,NaN,"January 13, 2021",2021,TV-MA,1 Season,"Crime TV Shows, Docuseries",Beneath the sunlit glamour of 1985 LA lurks a ...,4468,7
1528,s1529,Movie,Creating The Queen's Gambit,Sin director,NaN,NaN,"January 8, 2021",2021,TV-14,14 min,Documentaries,A fascinating character. Exquisite sets. A wig...,1528,8
4965,s4966,TV Show,Pretend It’s a City,Sin director,Fran Lebowitz,United States,"January 8, 2021",2021,TV-14,1 Season,Docuseries,Wander the New York City streets and fascinati...,4965,9
7551,s7552,Movie,What Happened to Mr. Cha?,Kim Dong-kyu,"Cha In-pyo, Cho Dal-hwan, Song Jae-ryong",South Korea,"January 1, 2021",2021,TV-MA,102 min,"Comedies, International Movies","With the peak of his career long behind him, a...",7551,9

### ***Subsetting based on text data***

In [74]:
net_peru = netflix[netflix.country == "Peru"]
net_peru.head(10)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,new_col,number
604,s605,Movie,Asu Mare 2,Ricardo Maldonado,"Carlos Alcántara, Emilia Drago, Christian Meie...",Peru,"December 1, 2016",2015,TV-14,100 min,"Comedies, International Movies",To win the heart of his true love – a high-soc...,604,4
4732,s4733,Movie,Pacificum: Return to the Ocean,"Mariana Tschudi, Héctor Gálvez",NaN,Peru,"June 15, 2018",2017,TV-G,74 min,"Documentaries, International Movies",Four scientists offer a sweeping yet intimate ...,4732,1
5634,s5635,Movie,Sinister Circle,Dorian Fernández-Moris,"Milene Vázquez, Matías Raygada, Claudia Dammer...",Peru,"October 1, 2019",2017,TV-MA,87 min,"Horror Movies, International Movies",A psychologist and her mute son confront evil ...,5634,2
2845,s2846,Movie,How to Get Over a Breakup,"Joanna Lombardi, Bruno Ascenzo","Gisela Ponce de León, Karina Jordán, Jely Reát...",Peru,"October 20, 2018",2018,TV-MA,104 min,"Comedies, International Movies, Romantic Movies","A heartbroken ad copywriter living in Lima, Pe...",2845,4

In [75]:
net_mex = netflix[netflix["country"] == "Mexico"]
net_mex

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,new_col,number
1949,s1950,TV Show,El Chavo,Sin director,"Roberto Gómez Bolaños, María Antonieta de las ...",Mexico,"December 31, 2017",1979,TV-PG,1 Season,"Classic & Cult TV, Kids' TV, Spanish-Language ...","El Chavo is a poor, nameless orphan who lives ...",1949,6
5697,s5698,Movie,Solo Con Tu Pareja,Alfonso Cuarón,"Luis de Icaza, Dobrina Liubomirova, Isabel Ben...",Mexico,"September 1, 2018",1991,NR,94 min,"Comedies, Independent Movies, International Mo...",A yuppie playboy looks for a quick death after...,5697,2
3639,s3640,Movie,Like Water for Chocolate,Alfonso Arau,"Marco Leonardi, Lumi Cavazos, Regina Torné, Ma...",Mexico,"November 1, 2019",1992,R,105 min,"Classic Movies, Dramas, International Movies","When Pedro marries her sister, Tita throws her...",3639,4
5526,s5527,Movie,"Sexo, Pudor y Lagrimas",Antonio Serrano,"Demián Bichir, Susana Zabaleta, Jorge Salinas,...",Mexico,"December 15, 2017",1999,R,111 min,"Comedies, Dramas, International Movies",Passions flare and alliances form when neighbo...,5526,4
7690,s7691,Movie,Y Tu Mamá También,Alfonso Cuarón,"Maribel Verdú, Gael García Bernal, Diego Luna,...",Mexico,"June 1, 2017",2001,R,106 min,"Dramas, Independent Movies, International Movies",When rich teens Tenoch and Julio meet the allu...,7690,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1742,s1743,TV Show,Diablero,Sin director,"Christopher Von Uckermann, Horacio García Roja...",Mexico,"January 31, 2020",2020,TV-MA,2 Seasons,"International TV Shows, Spanish-Language TV Sh...","When a young girl goes missing in a big city, ...",1742,8
1490,s1491,TV Show,Control Z,Sin director,"Ana Valeria Becerril, Michael Ronda, Yankel St...",Mexico,"May 22, 2020",2020,TV-MA,1 Season,"International TV Shows, Spanish-Language TV Sh...",When a hacker begins releasing students' secre...,1490,9
6464,s6465,TV Show,The House of Flowers,Sin director,"Verónica Castro, Aislinn Derbez, Cecilia Suáre...",Mexico,"April 23, 2020",2020,TV-MA,3 Seasons,"International TV Shows, Spanish-Language TV Sh...","In this dark comedy, a wealthy matriarch tries...",6464,9
4299,s4300,Movie,Mutiny of the Worker Bees,Carlos Morett,"Gustavo Egelhaaf, Alejandro Suárez, Bárbara de...",Mexico,"May 20, 2020",2020,TV-MA,94 min,"Comedies, International Movies",When Omar's grandfather forces him to get a jo...,4299,9
4173,s4174,TV Show,Monarca,Sin director,"Irene Azuela, Juan Manuel Bernal, Osvaldo Bena...",Mexico,"January 1, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Spanish-Language TV Sh...","After 20 years, Ana María returns to Mexico an...",4173,6

# ***Filtering Data***

### Checking unique values

In [76]:
netflix["country"].unique()

array([nan, 'United States', 'United States, United Kingdom', 'Egypt',
       'Italy, France', 'Italy', 'India', 'India, Malaysia',
       'United Kingdom, United States',
       'United States, Italy, United Kingdom, Liechtenstein', 'Poland',
       'Italy, United States',
       'United States, East Germany, West Germany',
       'United Kingdom, West Germany', 'Hong Kong, United States',
       'Hong Kong', 'United Kingdom', 'France', 'Lebanon', 'Poland,',
       'West Germany', 'Egypt, Algeria', 'Japan', 'Mexico',
       'Lebanon, Canada, France', 'Australia, United States',
       'Soviet Union, India', 'Kuwait', 'Australia', 'France, Lebanon',
       'India, Soviet Union', 'Poland, West Germany', 'Argentina',
       'United States, Japan',
       'Italy, South Africa, West Germany, Australia, United States',
       'Hong Kong, China', 'Denmark, France, Poland',
       'United States, Canada', 'Ireland, United Kingdom, United States',
       'France, Egypt', 'United States, Mexico', 'France, Belgium, Italy',
       'United States, Hong Kong', 'Australia, United Kingdom',
       'United Kingdom, Japan, United States', 'United States, France',
       'France, United Kingdom, India', 'United States, France, Mexico',
       'Argentina, Spain', 'Egypt, France',
       'United States, France, Japan', 'United States, Germany',
       'Canada, United States', 'United States, Germany, Mexico',
       'Canada', 'France, Norway, Lebanon, Belgium',
       'United States, Germany, Canada', 'Germany, United States',
       'Thailand', 'Germany, United States, United Kingdom, Canada',
       'United Kingdom, France', 'France, Japan, United States',
       'Taiwan, Hong Kong, United States, China',
       'Germany, Canada, United States',
       'United States, United Kingdom, Italy', 'Turkey', 'Indonesia',
       'United Kingdom, United States, France, Germany',
       'United States, United Arab Emirates', 'France, United States',
       'United States, Netherlands, Japan, France', 'Taiwan',
       'United States, Italy',
       'United Kingdom, Germany, Canada, United States',
       'South Africa, United States', 'Brazil, France, Germany',
       'New Zealand, United States', 'United States, New Zealand',
       'United States, Germany, United Kingdom',
       'United States, Australia', 'Malaysia',
       'United States, France, Canada, Spain', 'Colombia, United States',
       'India, France', 'Lebanon, France', 'South Korea',
       'United States, Czech Republic', 'United States, Canada, Germany',
       'Uruguay, Argentina, Germany, Spain',
       'Hong Kong, China, United States',
       'Germany, United States, Canada',
       'United States, United Kingdom, Germany',
       'Sweden, Czech Republic, United Kingdom, Denmark, Netherlands',
       'United Kingdom, Czech Republic, Germany, United States',
       'China, Hong Kong', 'United States, Germany, Australia',
       'United States, France, United Kingdom, Japan',
       'United Kingdom, United States, Japan', 'Romania',
       'United States, Czech Republic, United Kingdom', 'Netherlands',
       'United Kingdom, Czech Republic, United States, Germany, Bahamas',
       'United Kingdom, Thailand',
       'United States, Malta, France, United Kingdom',
       'Saudi Arabia, United Arab Emirates', 'Mexico, Spain',
       'France, United States, Mexico', 'Germany', 'Philippines',
       'Denmark', 'France, Lebanon, United Kingdom',
       'United Kingdom, Ireland', 'France, Belgium',
       'United States, United Kingdom, Canada', 'United Kingdom, India',
       'United States, New Zealand, Japan', 'Hong Kong, Taiwan',
       'Venezuela, Colombia', 'New Zealand, United Kingdom, Australia',
       'Norway', 'United States, South Africa',
       'United States, South Korea', 'Spain', 'Colombia',
       'United States, China', 'China', 'Colombia, Mexico, United States',
       'India, United States', 'Saudi Arabia',
       'Germany, United Kingdom, United States',
       'United Kingdom, Germany, United States',
       'United States, United Kingdom, France',
       'Czech Republic, United Kingdom, France',
       'France, Switzerland, Spain, United States, United Arab Emirates',
       'Singapore', 'Nigeria', 'United States, United Kingdom, Australia',
       'South Africa, United States, New Zealand, Canada',
       'United States, Germany, United Kingdom, Italy',
       'Spain, United Kingdom, United States',
       'United States, Germany, United Kingdom, Australia',
       'United States, Canada, France',
       'United Kingdom, Canada, France, United States',
       'United Kingdom, Canada', 'Germany, United States, France',
       'South Korea, United States', 'United States, Ireland',
       'Australia, France, Ireland',
       'France, United Kingdom, United States',
       'Canada, United States, India, United Kingdom',
       'Mexico, United States', 'Hong Kong, China, Singapore',
       'South Africa', 'India, Germany, France',
       'Romania, France, Switzerland, Germany',
       'United States, Canada, United Kingdom',
       'Germany, France, United States, Canada, United Kingdom',
       'India, Australia', 'United States, France, Italy, United Kingdom',
       'United States, United Kingdom, Canada, Japan',
       'United States, Australia, Mexico', 'India, Pakistan',
       'India, Japan', 'United Kingdom, United States, Australia',
       'Spain, Mexico, France', 'Germany, Sri Lanka',
       'United Kingdom, France, United States',
       'Ireland, Canada, United States, United Kingdom',
       'Japan, United States', 'Canada, Nigeria', 'Turkey, United States',
       'United Kingdom, Australia, Canada, United States',
       'United Kingdom, United States, Spain, Germany, Greece, Canada',
       'United Kingdom, Nigeria', 'Italy, Canada, France', 'Iran, France',
       'United States, Sweden, Norway',
       'United Kingdom, Germany, France, United States', 'Pakistan',
       'United States, India',
       'United States, New Zealand, United Kingdom',
       'France, Belgium, United States', 'India, Germany',
       'United States, Belgium, Canada',
       'Canada, United States, United Kingdom, France, Luxembourg',
       'Ireland, United States', 'United Kingdom, United States, France',
       'Brazil, United States', 'Brazil',
       'United States, India, Bangladesh', 'United Kingdom, Germany',
       'United States, Chile', 'United States, Russia', 'Israel',
       'Lebanon, United States, United Arab Emirates',
       'Spain, Thailand, United States',
       'United Kingdom, Denmark, Canada, Croatia',
       'Philippines, Canada, United Kingdom, United States',
       'Sweden, United Kingdom, Finland',
       'Germany, United States, Hong Kong, Singapore',
       'United Kingdom, Norway, Denmark, Germany, Sweden',
       'Saudi Arabia, Netherlands, Germany, Jordan, United Arab Emirates, United States',
       'Nigeria, United Kingdom', 'Canada, France, United States',
       'United States, Canada, Belgium, United Kingdom',
       'United States, Brazil', 'Indonesia, Singapore', 'Chile',
       'Israel, Germany, Poland, Luxembourg, Belgium, France, United States',
       'South Korea, Czech Republic',
       'Switzerland, United Kingdom, United States',
       'Denmark, Germany, Belgium, United Kingdom, France, Sweden',
       'Russia', 'Denmark, Germany, Belgium, United Kingdom, France',
       'United States, Spain', 'United States, France, Canada, Belgium',
       'Turkey, Azerbaijan', 'United States, Hungary, Ireland, Canada',
       'France, Belgium, Spain',
       'United States, Israel, Italy, South Africa',
       'United Kingdom, India, United States', 'Canada, Spain, France',
       'United States, United Kingdom, France, Germany, Japan',
       'United Kingdom, Egypt, United States',
       'Denmark, France, United States, Sweden', 'Australia, France',
       'United States, China, Hong Kong', 'India, Switzerland',
       'India, Canada', 'Canada, India', 'United Kingdom,',
       'France, Germany, Switzerland', 'Pakistan, Norway, United States',
       'United States, France, Canada, Lebanon, Qatar',
       'Denmark, Brazil, France, Portugal, Sweden',
       'Canada, France, Italy, Morocco, United States',
       'Denmark, Zimbabwe', 'United Kingdom, China, United States',
       'Canada, Luxembourg', 'Germany, United Kingdom',
       'Canada, United Kingdom, United States',
       'Canada, Germany, France, United States',
       'Denmark, Indonesia, Finland, Norway, United Kingdom, Israel, France, United States, Germany, Netherlands',
       'United Arab Emirates',
       'United States, United Kingdom, Canada, China',
       'Bulgaria, United States, Spain, Canada',
       'United Arab Emirates, United States', 'Norway, United States',
       'United States, France, Serbia', 'Vietnam',
       'United Arab Emirates, Jordan, Lebanon',
       'United Kingdom, France, Canada, Belgium, United States',
       'United States, Greece, United Kingdom',
       'United Kingdom, Brazil, Germany',
       'United States, Bermuda, Ecuador',
       'Norway, United Kingdom, France, Ireland',
       'Australia, United Kingdom, United States, New Zealand, Italy, France',
       'Lebanon, United Arab Emirates, France, Switzerland, Germany',
       'United Kingdom, United States, Morocco',
       'Thailand, Canada, United States',
       'Australia, United Kingdom, Canada', 'Kenya, United States',
       'Germany, United States, Italy',
       'Denmark, United Kingdom, South Africa, Sweden, Belgium',
       'Austria, Czech Republic',
       'United States, United Kingdom, Denmark, Sweden',
       'Russia, United States', 'Norway, Denmark, Sweden',
       'Canada, South Korea, United States',
       'United States, Japan, Canada',
       'United States, India, United Arab Emirates',
       'United Kingdom, Canada, United States', 'France, Canada, Belgium',
       'South Korea, China, United States',
       'Canada, United Kingdom, Netherlands', 'United States, Senegal',
       'China, Germany, India, United States',
       'France, Canada, Italy, United States, China', 'Australia, Iraq',
       'France, Morocco',
       'Ireland, United Kingdom, Greece, France, Netherlands',
       'United States, Canada, Japan, Panama',
       'Australia, United Kingdom, United Arab Emirates, Canada',
       'Malaysia, Singapore, Hong Kong', 'United Arab Emirates, Jordan',
       'Japan, Canada', 'Switzerland', 'Lebanon, Qatar', 'Mexico, France',
       'Germany, Australia, France, China', 'United States, Morocco',
       'Peru', 'Romania, Bulgaria, Hungary', 'United Kingdom, Lithuania',
       'Croatia, Slovenia, Serbia, Montenegro', 'France, Germany',
       'Canada, Mexico, Germany, South Africa',
       'United States, United Kingdom, Morocco',
       'United States, Spain, Germany', 'Canada, Australia',
       'Argentina, Chile, Peru', 'Israel, Sweden, Germany, Netherlands',
       'United Kingdom, South Korea',
       'Netherlands, Belgium, United Kingdom, United States',
       'New Zealand', 'Denmark, United Kingdom, Sweden',
       'United States, Nicaragua', 'United States, Indonesia', 'Belgium',
       'United Kingdom, United States, Germany, Denmark, Belgium, Japan',
       'United States, United Kingdom, Spain, South Korea',
       'United States, Ireland, United Kingdom, India',
       'Chile, Spain, Argentina, Germany', 'United States, Sweden',
       'Germany, France, Luxembourg, United Kingdom, United States',
       'Russia, Spain', 'United States, Uruguay',
       'United Kingdom, Ukraine, United States',
       'United States, Argentina',
       'United Kingdom, Russia, United States', 'Pakistan, United States',
       'France, Malta, United States',
       'Canada, United States, United Kingdom', 'Ireland', 'Ukraine',
       'Ireland, Canada, United Kingdom, United States',
       'United States, Chile, Israel', 'Russia, United States, China',
       'Israel, United States', 'United Kingdom, New Zealand',
       'Spain, France, Uruguay', 'France, United States, Canada',
       'China, South Korea, United States', 'Iceland',
       'Canada, United States, France',
       'Netherlands, Denmark, South Africa', 'Netherlands, Belgium',
       'Czech Republic, France', 'Ireland, United Kingdom',
       'United States, Greece', 'Germany, Jordan, Netherlands',
       'France, Canada, China, Cambodia', 'Canada, United Kingdom',
       'United Kingdom, Germany, Canada', 'France, South Korea, Japan',
       'South Africa, United States, Germany',
       'Canada, India, Thailand, United States, United Arab Emirates',
       'Netherlands, Belgium, Germany, Jordan', 'Denmark, China',
       'United States, Canada, China', 'United States, Canada, Ireland',
       'India, United Kingdom', 'United States, Venezuela',
       'Chile, Argentina, France, Spain, United States',
       'United Kingdom, South Africa', 'Belgium, France',
       'United Kingdom, France, Germany, United States',
       'Serbia, South Korea, Slovenia', 'Italy, Germany',
       'United Kingdom, Spain, Belgium', 'Canada, Spain',
       'United States, Spain, Italy', 'Chile, United States, France',
       'Austria', 'Australia, India', 'France, Qatar',
       'Peru, United States, United Kingdom', 'Sweden', 'Chile, France',
       'Philippines, Qatar', 'Finland, Sweden, Norway, Latvia, Germany',
       'United States, Greece, Brazil', 'Hungary', 'China, United States',
       'France, Germany, Czech Republic, Belgium',
       'United States, Cambodia', 'Netherlands, Denmark, France, Germany',
       'Norway, Germany', 'United States, Kazakhstan',
       'Czech Republic, Slovakia',
       'Brazil, Netherlands, United States, Colombia, Austria, Germany',
       'United States, United Kingdom, Japan', 'Sweden, United States',
       'United Kingdom, France, United States, Belgium, Luxembourg, China, Germany',
       'United Arab Emirates, Romania', 'South Korea, France',
       'Portugal, France, Poland, United States', 'Belarus',
       'Spain, United States', 'Spain, Italy, Argentina',
       'Spain, Argentina', 'Turkey, India',
       'United Kingdom, Germany, United Arab Emirates, New Zealand',
       'United States, South Korea, China',
       'United Kingdom, Spain, United States',
       'United Kingdom, France, Germany',
       'China, Hong Kong, United States', 'Spain, Mexico',
       'Turkey, France, Germany, Poland', 'South Korea, China',
       'United Kingdom, Israel, Russia', 'Spain, Switzerland',
       'United Kingdom, Hong Kong',
       'Slovenia, Croatia, Germany, Czech Republic, Qatar',
       'Denmark, United States', 'United Kingdom, France, Belgium',
       'United Kingdom, Poland, United States',
       'Ireland, United Kingdom, Italy, United States', 'France, Canada',
       'United Kingdom, Canada, Italy',
       'United Kingdom, Italy, Israel, Peru, United States',
       'Denmark, Spain', 'France, Canada, United States',
       'Bulgaria, United States', 'United Kingdom, Russia',
       'United States, Hungary', 'United States, Bulgaria',
       'Canada, Ireland, United States', 'Israel, Germany, France',
       'United Kingdom, Jordan, Qatar, Iran',
       'South Korea, Canada, United States, China', 'Singapore, France',
       'United States, France, South Korea, Indonesia',
       'Switzerland, France', 'Italy, India', 'United States, Botswana',
       'Spain, Cuba', 'Portugal, Spain',
       'Belgium, Ireland, Netherlands, Germany, Afghanistan',
       'United Kingdom, Finland, Germany', 'Canada, France',
       'Ireland, South Africa', 'United States, Iceland',
       'Denmark, Sweden, Israel, United States', 'Australia, Canada',
       'Australia, Armenia, Japan, Jordan, Mexico, Mongolia, New Zealand, Philippines, South Africa, Sweden, United States, Uruguay',
       'Australia, United Arab Emirates',
       'Brazil, India, China, United States', 'Serbia, United States',
       'Germany, Australia',
       'United States, Australia, Samoa, United Kingdom',
       'Italy, United States, Argentina', 'Zimbabwe',
       'United Kingdom, Canada, Japan', 'India, Mexico',
       'Germany, France, Russia',
       'Netherlands, Germany, Denmark, United Kingdom',
       'Ireland, Canada, Luxembourg, United States, United Kingdom, Philippines, India',
       'Brazil, France', 'France, Belgium, China, United States',
       'Cambodia, United States', 'China, Canada, United States',
       'United Kingdom, France, Belgium, Canada, United States',
       'Saudi Arabia, Syria, Egypt, Lebanon, Kuwait',
       'Greece, United States', 'Austria, United States', 'Guatemala',
       'Sweden, Netherlands', 'Israel, Germany', 'South Africa, Nigeria',
       'Argentina, Brazil, France, Poland, Germany, Denmark', 'Cyprus',
       'Canada, Germany, South Africa',
       'United States, Canada, Indonesia, United Kingdom, China, Singapore',
       'Somalia, Kenya, Sudan, South Africa, United States',
       'United Kingdom, Namibia, South Africa, Zimbabwe, United States',
       'Argentina, Uruguay, Spain, France',
       'United Kingdom, France, Belgium, United States',
       'Italy, France, Switzerland', 'United States, Denmark', 'Ghana',
       'Singapore, United States',
       'Australia, New Zealand, United States',
       'South Africa, Germany, Netherlands, France', 'Argentina, France',
       'Germany, Belgium', 'United States, South Korea, Japan',
       'Venezuela', 'United States, Colombia, Mexico',
       'Indonesia, Netherlands', 'Cambodia',
       'United Kingdom, India, Sweden',
       'Spain, Belgium, Switzerland, United States, China, United Kingdom',
       'Czech Republic, United States',
       'United Arab Emirates, United States, United Kingdom',
       'Germany, Italy', 'Chile, Peru', 'Norway, Germany, Sweden',
       'Uruguay', 'New Zealand, United Kingdom',
       'United Kingdom, United States, Canada', 'Spain, United Kingdom',
       'Spain, Canada, United States',
       'United Kingdom, France, United States, Belgium', 'Spain, Germany',
       'China, India, Nepal', 'Argentina, Italy',
       'Switzerland, France, Belgium, United States',
       'United Kingdom, United States, Dominican Republic',
       'France, Japan', 'Peru, Germany, Norway',
       'United Kingdom, China, United States, India', 'Spain, Colombia',
       'Canada, Japan, Netherlands', 'Thailand, United States',
       'United States, Australia, China',
       'Netherlands, Germany, Italy, Canada', 'Argentina, Chile',
       'United Kingdom, Singapore',
       'Argentina, France, United States, Germany, Qatar',
       'Netherlands, United States',
       'France, Netherlands, South Africa, Finland',
       'South Africa, China, United States', 'Italy, Turkey',
       'United States, Australia, South Africa, United Kingdom',
       'Georgia, Germany, France', 'Switzerland, United States',
       'China, Japan', 'Spain, France', 'Jamaica, United States',
       'Indonesia, United States', 'Japan, Canada, United States',
       'India, Germany, Austria', 'Spain, Portugal',
       'Ireland, United States, France', 'Germany, United States, Sweden',
       'United States, China, Colombia',
       'Taiwan, China, France, United States', 'Uruguay, Spain, Mexico',
       'United States, Colombia',
       'United Arab Emirates, United Kingdom, India',
       'United Kingdom, Pakistan', 'Pakistan, United Arab Emirates',
       'Ireland, Canada', 'Spain, Belgium',
       'Austria, Iraq, United States', 'Canada, United States, Germany',
       'Bangladesh', 'Paraguay, Argentina', 'Ghana, United States',
       'Mexico, Netherlands', 'United States, China, Canada',
       'Colombia, Mexico', 'United Kingdom, Belgium',
       'United States, Brazil, South Korea, Mexico, Japan, Germany',
       'France, China, Japan, United States', 'Georgia',
       'China, United States, United Kingdom',
       'Italy, Switzerland, Albania, Poland',

In [38]:
netflix.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7787 entries, 0 to 7786
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       7787 non-null   object
 1   type          7787 non-null   object
 2   title         7787 non-null   object
 3   director      7787 non-null   object
 4   cast          7069 non-null   object
 5   country       7280 non-null   object
 6   date_added    7777 non-null   object
 7   release_year  7787 non-null   int64
 8   rating        7780 non-null   object
 9   duration      7787 non-null   object
 10  listed_in     7787 non-null   object
 11  description   7787 non-null   object
 12  new_col       7787 non-null   int32
 13  number        7787 non-null   int32
dtypes: int32(2), int64(1), object(11)
memory usage: 791.0+ KB

In [39]:
netflix.head(3)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,new_col,number
0,s1,TV Show,3%,Sin director,"João Miguel, Bianca Comparato, Michel Gomes, R...",Brazil,"August 14, 2020",2020,TV-MA,4 Seasons,"International TV Shows, TV Dramas, TV Sci-Fi &...",In a future where the elite inhabit an island ...,0,3
1,s2,Movie,7:19,Jorge Michel Grau,"Demián Bichir, Héctor Bonilla, Oscar Serrano, ...",Mexico,"December 23, 2016",2016,TV-MA,93 min,"Dramas, International Movies",After a devastating earthquake hits Mexico Cit...,1,3
2,s3,Movie,23:59,Gilbert Chan,"Tedd Chan, Stella Chung, Henley Hii, Lawrence ...",Singapore,"December 20, 2018",2011,R,78 min,"Horror Movies, International Movies","When an army recruit is found dead, his fellow...",2,7

### Example

In [40]:
netflix[netflix.type == "TV Show"].head(4)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,new_col,number
0,s1,TV Show,3%,Sin director,"João Miguel, Bianca Comparato, Michel Gomes, R...",Brazil,"August 14, 2020",2020,TV-MA,4 Seasons,"International TV Shows, TV Dramas, TV Sci-Fi &...",In a future where the elite inhabit an island ...,0,3
5,s6,TV Show,46,Serdar Akar,"Erdal Beşikçioğlu, Yasemin Allen, Melis Birkan...",Turkey,"July 1, 2017",2016,TV-MA,1 Season,"International TV Shows, TV Dramas, TV Mysteries",A genetics professor experiments with a treatm...,5,9
11,s12,TV Show,1983,Sin director,"Robert Więckiewicz, Maciej Musiał, Michalina O...","Poland, United States","November 30, 2018",2018,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Dramas","In this dark alt-history thriller, a naïve law...",11,5
12,s13,TV Show,1994,Diego Enrique Osorno,NaN,Mexico,"May 17, 2019",2019,TV-MA,1 Season,"Crime TV Shows, Docuseries, International TV S...",Archival video and new interviews examine Mexi...,12,2

In [41]:
len( netflix.loc[netflix["type"] == "TV Show"] )

2410

In [77]:
netflix[(netflix["type"] == "TV Show") & (netflix["country"] == "Peru")]

Empty DataFrame
Columns: [show_id, type, title, director, cast, country, date_added, release_year, rating, duration, listed_in, description, new_col, number]
Index: []

In [78]:
# No hay series peruanas en Netflix

len(netflix[(netflix["country"] == "Brazil") | (netflix["country"] == "Peru")])

76

In [80]:
netflix[(netflix["type"] == "TV Show") | (netflix["country"] == "Peru")]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,new_col,number
4867,s4868,TV Show,Pioneers: First Women Filmmakers*,Sin director,NaN,NaN,"December 30, 2018",1925,TV-14,1 Season,TV Shows,This collection restores films from women who ...,4867,4
4866,s4867,TV Show,Pioneers of African-American Cinema,"Oscar Micheaux, Spencer Williams, Richard E. N...",NaN,United States,"February 1, 2017",1946,TV-14,1 Season,TV Shows,This newly preserved collection features more ...,4866,6
6953,s6954,TV Show,The Twilight Zone (Original Series),Sin director,Rod Serling,United States,"July 1, 2017",1963,TV-14,4 Seasons,"Classic & Cult TV, TV Sci-Fi & Fantasy","Hosted by creator Rod Serling, this groundbrea...",6953,1
6082,s6083,TV Show,The Andy Griffith Show,Sin director,"Andy Griffith, Ron Howard, Don Knotts, Frances...",United States,"July 1, 2017",1967,TV-G,8 Seasons,"Classic & Cult TV, TV Comedies",Homespun humor and easygoing Sheriff Andy Tayl...,6082,1
5785,s5786,TV Show,Star Trek,Sin director,"William Shatner, Leonard Nimoy, DeForest Kelle...",United States,"October 1, 2017",1968,TV-14,3 Seasons,"Classic & Cult TV, TV Action & Adventure, TV S...","Led by unflappable Capt. Kirk, the crew of the...",5785,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2327,s2328,TV Show,Gabby's Dollhouse,Sin director,"Laila Lockhart Kraner, Tucker Chandler, Juliet...",NaN,"January 5, 2021",2021,TV-Y,1 Season,Kids' TV,"Cute cats, quirky crafts and colorful magic! J...",2327,6
2741,s2742,TV Show,Hilda,Sin director,"Bella Ramsey, Ameerah Falzon-Ojo, Oliver Nelso...","United Kingdom, Canada, United States","December 14, 2020",2021,TV-Y7,2 Seasons,Kids' TV,"Fearless, free-spirited Hilda finds new friend...",2741,7
1864,s1865,TV Show,Dream Home Makeover,Sin director,NaN,United States,"January 1, 2021",2021,TV-G,2 Seasons,Reality TV,Dreams come true for real families looking for...,1864,7
4468,s4469,TV Show,Night Stalker: The Hunt for a Serial Killer,Tiller Russell,NaN,NaN,"January 13, 2021",2021,TV-MA,1 Season,"Crime TV Shows, Docuseries",Beneath the sunlit glamour of 1985 LA lurks a ...,4468,7
4965,s4966,TV Show,Pretend It’s a City,Sin director,Fran Lebowitz,United States,"January 8, 2021",2021,TV-14,1 Season,Docuseries,Wander the New York City streets and fascinati...,4965,9

In [81]:
# peliculas americanas
netflix.loc[(netflix["type"] == "Movie") & (netflix["country"] == "United States") 
            & (netflix["release_year"] > 2019)].head(5)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,new_col,number
154,s155,Movie,A California Christmas,Shaun Paul Piccinino,"Lauren Swickard, Josh Swickard, Ali Afshar, Da...",United States,"December 14, 2020",2020,PG-13,107 min,"Comedies, Romantic Movies","With his carefree lifestyle on the line, a wea...",154,1
611,s612,Movie,Athlete A,"Bonni Cohen, Jon Shenk",NaN,United States,"June 24, 2020",2020,PG-13,104 min,"Documentaries, Sports Movies",This documentary focuses on the gymnasts who s...,611,1
1135,s1136,Movie,Bulletproof 2,Don Michael Paul,"Faizon Love, Kirk Fox, Tony Todd, Pearl Thusi,...",United States,"January 9, 2020",2020,TV-MA,97 min,"Action & Adventure, Comedies",A special agent abruptly reunites with a crimi...,1135,1
1569,s1570,Movie,Da 5 Bloods,Spike Lee,"Delroy Lindo, Jonathan Majors, Clarke Peters, ...",United States,"June 12, 2020",2020,R,156 min,"Action & Adventure, Dramas",Four African American veterans return to Vietn...,1569,1
7370,s7371,Movie,Uppity: The Willy T. Ribbs Story,"Nate Adams, Adam Carolla",Willy T. Ribbs,United States,"February 5, 2020",2020,TV-MA,106 min,"Documentaries, Sports Movies",This documentary profiles a defiant driver who...,7370,1

In [128]:
# Brazil in 2020
net_B_2020 = netflix[(netflix["country"] == "Brazil") & (netflix["release_year"] == 2020)]
net_B_2020.head(3)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,new_col,number
0,s1,TV Show,3%,NaN,"João Miguel, Bianca Comparato, Michel Gomes, R...",Brazil,"August 14, 2020",2020,TV-MA,4 Seasons,"International TV Shows, TV Dramas, TV Sci-Fi &...",In a future where the elite inhabit an island ...,0,5
218,s219,TV Show,A Queen Is Born,Carla Barros,"Gloria Groove, Alexia Twister",Brazil,"November 11, 2020",2020,TV-14,1 Season,"International TV Shows, Reality TV",Gloria Groove and Alexia Twister make drag dre...,218,4
320,s321,Movie,Afonso Padilha: Classless,"Junior Carelli, Rudge Campos",Afonso Padilha,Brazil,"September 3, 2020",2020,TV-MA,63 min,Stand-Up Comedy,Brazilian comedian Afonso Padilha dives into h...,320,8

# .isin()
If you want to filter by multiple values of a categorical variable, the easiest way is to use the isin() method.

In [82]:
# Peliculas de Perú y Chile

net_per_ch = netflix[netflix["country"].isin(["Peru","Chile"])] # filter by variables's values
net_per_ch

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,new_col,number
1962,s1963,TV Show,El Reemplazante,Sin director,"Iván Álvarez de Araya, Blanca Lewin, Karla Mel...",Chile,"April 4, 2020",2013,TV-MA,2 Seasons,"International TV Shows, Spanish-Language TV Sh...",A former high-ranking financial executive find...,1962,2
754,s755,Movie,Barrio Universitario,Esteban Vidal,"Fabrizio Copano, Rodrigo Salinas, Pedro Rumino...",Chile,"August 19, 2018",2013,TV-14,91 min,"Comedies, International Movies",Four friends from a humble technical school co...,754,6
604,s605,Movie,Asu Mare 2,Ricardo Maldonado,"Carlos Alcántara, Emilia Drago, Christian Meie...",Peru,"December 1, 2016",2015,TV-14,100 min,"Comedies, International Movies",To win the heart of his true love – a high-soc...,604,4
2564,s2565,Movie,Héroes,Esteban Vidal,"Fabrizio Copano, Juanita Ringeling, Fernando A...",Chile,"August 19, 2018",2015,TV-MA,91 min,"Comedies, International Movies","When an earthquake hits Chile, rescue workers ...",2564,4
3227,s3228,TV Show,Juana Brava,Sin director,"Elisa Zulueta, Alejandro Trejo, Lucas Balmaced...",Chile,"March 20, 2017",2015,TV-MA,1 Season,"International TV Shows, Spanish-Language TV Sh...","After many years away, a woman returns to her ...",3227,8
618,s619,Movie,Attitude Test,"Fabrizio Copano, Augusto Matte","Belén Soto, Denise Rosenthal, Constanza Piccol...",Chile,"August 19, 2018",2016,TV-14,88 min,"Comedies, Independent Movies, International Mo...",Four high school seniors steal an important co...,618,2
3850,s3851,Movie,Madre,Aaron Burns,"Daniela Ramírez, Cristobal Tapia Montt, Aida, ...",Chile,"August 26, 2017",2016,TV-MA,95 min,"International Movies, Thrillers","Pregnant and overwhelmed, Diana hires a careta...",3850,7
707,s708,TV Show,Bala Loca,Sin director,"Alejandro Goic, Trinidad González, Ingrid Isen...",Chile,"April 1, 2017",2016,TV-MA,1 Season,"International TV Shows, Spanish-Language TV Sh...",A veteran journalist starting a news site abou...,707,8
4732,s4733,Movie,Pacificum: Return to the Ocean,"Mariana Tschudi, Héctor Gálvez",NaN,Peru,"June 15, 2018",2017,TV-G,74 min,"Documentaries, International Movies",Four scientists offer a sweeping yet intimate ...,4732,1
5634,s5635,Movie,Sinister Circle,Dorian Fernández-Moris,"Milene Vázquez, Matías Raygada, Claudia Dammer...",Peru,"October 1, 2019",2017,TV-MA,87 min,"Horror Movies, International Movies",A psychologist and her mute son confront evil ...,5634,2
2086,s2087,Movie,Fabrizio Copano: Solo pienso en mi,"Rodrigo Toro, Francisco Schultz",Fabrizio Copano,Chile,"September 8, 2017",2017,TV-MA,60 min,Stand-Up Comedy,Fabrizio Copano takes audience participation t...,2086,7
4415,s4416,Movie,Natalia Valdebenito: El especial,"Raúl Campos, Jan Suter",Natalia Valdebenito,Chile,"March 2, 2018",2018,TV-MA,69 min,Stand-Up Comedy,A Chilean comedian fuses activism with irrever...,4415,3
3123,s3124,Movie,Jani Dueñas: Grandes fracasos de ayer y hoy,"Raúl Campos, Jan Suter",Jani Dueñas,Chile,"June 29, 2018",2018,TV-MA,77 min,Stand-Up Comedy,Chilean comedian and personality Jani Dueñas p...,3123,3
2845,s2846,Movie,How to Get Over a Breakup,"Joanna Lombardi, Bruno Ascenzo","Gisela Ponce de León, Karina Jordán, Jely Reát...",Peru,"October 20, 2018",2018,TV-MA,104 min,"Comedies, International Movies, Romantic Movies","A heartbroken ad copywriter living in Lima, Pe...",2845,4
4486,s4487,Movie,No Estoy Loca,Nicolás López,"Paz Bascuñán, Marcial Tagle, Antonia Zegers, C...",Chile,"May 4, 2018",2018,TV-MA,116 min,"Comedies, Dramas, International Movies",A woman enters a quirky mental health clinic a...,4486,6
4272,s4273,Movie,Mujeres arriba,Andrés Feddersen,"Loretto Bernal, Natalia Valdebenito, Alison Ma...",Chile,"May 21, 2020",2019,TV-14,98 min,"Comedies, International Movies, Romantic Movies",A trio of best friends — a carefree bacheloret...,4272,4
4061,s4062,Movie,Mi amigo Alexis,Alejandro Fernández Almendras,"Luciano González, Alexis Sánchez, Daniel Muñoz...",Chile,"August 30, 2019",2019,TV-PG,102 min,"Children & Family Movies, Comedies, Dramas",When a young soccer fan and his idol forge an ...,4061,6
4499,s4500,Movie,Nobody Knows I'm Here,Gaspar Antillo,"Jorge García, Millaray Lobos, Luis Gnecco, Ale...",Chile,"June 24, 2020",2020,TV-MA,92 min,"Dramas, Independent Movies, International Movies","A former child singer, traumatized by his expe...",4499,8

In [83]:
# Peliculas diferentes de Perú y Chile

netflix[~ netflix["country"].isin(["Peru","Chile"])]   # ~ negación en Python ALT + 126

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,new_col,number
4867,s4868,TV Show,Pioneers: First Women Filmmakers*,Sin director,NaN,NaN,"December 30, 2018",1925,TV-14,1 Season,TV Shows,This collection restores films from women who ...,4867,4
4960,s4961,Movie,Prelude to War,Frank Capra,NaN,United States,"March 31, 2017",1942,TV-14,52 min,"Classic Movies, Documentaries",Frank Capra's documentary chronicles the rise ...,4960,7
6117,s6118,Movie,The Battle of Midway,John Ford,"Henry Fonda, Jane Darwell",United States,"March 31, 2017",1942,TV-14,18 min,"Classic Movies, Documentaries",Director John Ford captures combat footage of ...,6117,8
7616,s7617,Movie,Why We Fight: The Battle of Russia,"Frank Capra, Anatole Litvak",NaN,United States,"March 31, 2017",1943,TV-PG,82 min,Documentaries,This installment of Frank Capra's acclaimed do...,7616,2
7342,s7343,Movie,Undercover: How to Operate Behind Enemy Lines,John Ford,NaN,United States,"March 31, 2017",1943,TV-PG,61 min,"Classic Movies, Documentaries",This World War II-era training film dramatizes...,7342,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1864,s1865,TV Show,Dream Home Makeover,Sin director,NaN,United States,"January 1, 2021",2021,TV-G,2 Seasons,Reality TV,Dreams come true for real families looking for...,1864,7
4468,s4469,TV Show,Night Stalker: The Hunt for a Serial Killer,Tiller Russell,NaN,NaN,"January 13, 2021",2021,TV-MA,1 Season,"Crime TV Shows, Docuseries",Beneath the sunlit glamour of 1985 LA lurks a ...,4468,7
1528,s1529,Movie,Creating The Queen's Gambit,Sin director,NaN,NaN,"January 8, 2021",2021,TV-14,14 min,Documentaries,A fascinating character. Exquisite sets. A wig...,1528,8
4965,s4966,TV Show,Pretend It’s a City,Sin director,Fran Lebowitz,United States,"January 8, 2021",2021,TV-14,1 Season,Docuseries,Wander the New York City streets and fascinati...,4965,9
7551,s7552,Movie,What Happened to Mr. Cha?,Kim Dong-kyu,"Cha In-pyo, Cho Dal-hwan, Song Jae-ryong",South Korea,"January 1, 2021",2021,TV-MA,102 min,"Comedies, International Movies","With the peak of his career long behind him, a...",7551,9

## Alternative methods to filter

In [84]:
movie = netflix["type"] == "Movie"
m_usa = netflix["country"] == "United States"
m_actual = netflix["release_year"] > 2019

movie_usa = netflix[movie & m_usa & m_actual]
movie_usa

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,new_col,number
154,s155,Movie,A California Christmas,Shaun Paul Piccinino,"Lauren Swickard, Josh Swickard, Ali Afshar, Da...",United States,"December 14, 2020",2020,PG-13,107 min,"Comedies, Romantic Movies","With his carefree lifestyle on the line, a wea...",154,1
611,s612,Movie,Athlete A,"Bonni Cohen, Jon Shenk",NaN,United States,"June 24, 2020",2020,PG-13,104 min,"Documentaries, Sports Movies",This documentary focuses on the gymnasts who s...,611,1
1135,s1136,Movie,Bulletproof 2,Don Michael Paul,"Faizon Love, Kirk Fox, Tony Todd, Pearl Thusi,...",United States,"January 9, 2020",2020,TV-MA,97 min,"Action & Adventure, Comedies",A special agent abruptly reunites with a crimi...,1135,1
1569,s1570,Movie,Da 5 Bloods,Spike Lee,"Delroy Lindo, Jonathan Majors, Clarke Peters, ...",United States,"June 12, 2020",2020,R,156 min,"Action & Adventure, Dramas",Four African American veterans return to Vietn...,1569,1
7370,s7371,Movie,Uppity: The Willy T. Ribbs Story,"Nate Adams, Adam Carolla",Willy T. Ribbs,United States,"February 5, 2020",2020,TV-MA,106 min,"Documentaries, Sports Movies",This documentary profiles a defiant driver who...,7370,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2434,s2435,Movie,Giving Voice,"James D. Stern, Fernando Villena","Viola Davis, Denzel Washington, Stephen Hender...",United States,"December 11, 2020",2020,PG-13,91 min,Documentaries,Six ambitious student actors audition for the ...,2434,9
3830,s3831,Movie,Ma Rainey's Black Bottom,George C. Wolfe,"Viola Davis, Chadwick Boseman, Glynn Turman, C...",United States,"December 18, 2020",2020,R,94 min,"Dramas, Music & Musicals",Tensions and temperatures rise at a Chicago mu...,3830,9
6670,s6671,Movie,The Minimalists: Less Is Now,Sin director,NaN,United States,"January 1, 2021",2021,TV-14,54 min,Documentaries,They've built a movement out of minimalism. Lo...,6670,1
7569,s7570,Movie,What Would Sophia Loren Do?,Ross Kauffman,"Nancy ""Vincenza Careri"" Kulik, Sophia Loren",United States,"January 15, 2021",2021,TV-14,32 min,Documentaries,"In this delightful short documentary, an Itali...",7569,4
1514,s1515,Movie,"Crack: Cocaine, Corruption & Conspiracy",Stanley Nelson,NaN,United States,"January 11, 2021",2021,TV-MA,90 min,Documentaries,"A cheap, powerful drug emerges during a recess...",1514,7

In [85]:
movie_usa = netflix.loc[ ( netflix[ "type" ] == "Movie" ) & ( netflix[ "country" ] == "United States") & ( netflix[ "release_year" ] > 2019 ) ]

In [86]:
movie_usa

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,new_col,number
154,s155,Movie,A California Christmas,Shaun Paul Piccinino,"Lauren Swickard, Josh Swickard, Ali Afshar, Da...",United States,"December 14, 2020",2020,PG-13,107 min,"Comedies, Romantic Movies","With his carefree lifestyle on the line, a wea...",154,1
611,s612,Movie,Athlete A,"Bonni Cohen, Jon Shenk",NaN,United States,"June 24, 2020",2020,PG-13,104 min,"Documentaries, Sports Movies",This documentary focuses on the gymnasts who s...,611,1
1135,s1136,Movie,Bulletproof 2,Don Michael Paul,"Faizon Love, Kirk Fox, Tony Todd, Pearl Thusi,...",United States,"January 9, 2020",2020,TV-MA,97 min,"Action & Adventure, Comedies",A special agent abruptly reunites with a crimi...,1135,1
1569,s1570,Movie,Da 5 Bloods,Spike Lee,"Delroy Lindo, Jonathan Majors, Clarke Peters, ...",United States,"June 12, 2020",2020,R,156 min,"Action & Adventure, Dramas",Four African American veterans return to Vietn...,1569,1
7370,s7371,Movie,Uppity: The Willy T. Ribbs Story,"Nate Adams, Adam Carolla",Willy T. Ribbs,United States,"February 5, 2020",2020,TV-MA,106 min,"Documentaries, Sports Movies",This documentary profiles a defiant driver who...,7370,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2434,s2435,Movie,Giving Voice,"James D. Stern, Fernando Villena","Viola Davis, Denzel Washington, Stephen Hender...",United States,"December 11, 2020",2020,PG-13,91 min,Documentaries,Six ambitious student actors audition for the ...,2434,9
3830,s3831,Movie,Ma Rainey's Black Bottom,George C. Wolfe,"Viola Davis, Chadwick Boseman, Glynn Turman, C...",United States,"December 18, 2020",2020,R,94 min,"Dramas, Music & Musicals",Tensions and temperatures rise at a Chicago mu...,3830,9
6670,s6671,Movie,The Minimalists: Less Is Now,Sin director,NaN,United States,"January 1, 2021",2021,TV-14,54 min,Documentaries,They've built a movement out of minimalism. Lo...,6670,1
7569,s7570,Movie,What Would Sophia Loren Do?,Ross Kauffman,"Nancy ""Vincenza Careri"" Kulik, Sophia Loren",United States,"January 15, 2021",2021,TV-14,32 min,Documentaries,"In this delightful short documentary, an Itali...",7569,4
1514,s1515,Movie,"Crack: Cocaine, Corruption & Conspiracy",Stanley Nelson,NaN,United States,"January 11, 2021",2021,TV-MA,90 min,Documentaries,"A cheap, powerful drug emerges during a recess...",1514,7

In [88]:
movie_usa.drop(['show_id', 'director'], axis=1, inplace = True ) # axis = 1 , drop por columna

C:\Users\Roberto\AppData\Local\Temp\ipykernel_27528\3584590493.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movie_usa.drop(['show_id', 'director'], axis=1, inplace = True ) # axis = 1 , drop por columna

In [89]:
movie_usa

,type,title,cast,country,date_added,release_year,rating,duration,listed_in,description,new_col,number
154,Movie,A California Christmas,"Lauren Swickard, Josh Swickard, Ali Afshar, Da...",United States,"December 14, 2020",2020,PG-13,107 min,"Comedies, Romantic Movies","With his carefree lifestyle on the line, a wea...",154,1
611,Movie,Athlete A,NaN,United States,"June 24, 2020",2020,PG-13,104 min,"Documentaries, Sports Movies",This documentary focuses on the gymnasts who s...,611,1
1135,Movie,Bulletproof 2,"Faizon Love, Kirk Fox, Tony Todd, Pearl Thusi,...",United States,"January 9, 2020",2020,TV-MA,97 min,"Action & Adventure, Comedies",A special agent abruptly reunites with a crimi...,1135,1
1569,Movie,Da 5 Bloods,"Delroy Lindo, Jonathan Majors, Clarke Peters, ...",United States,"June 12, 2020",2020,R,156 min,"Action & Adventure, Dramas",Four African American veterans return to Vietn...,1569,1
7370,Movie,Uppity: The Willy T. Ribbs Story,Willy T. Ribbs,United States,"February 5, 2020",2020,TV-MA,106 min,"Documentaries, Sports Movies",This documentary profiles a defiant driver who...,7370,1
...,...,...,...,...,...,...,...,...,...,...,...,...
2434,Movie,Giving Voice,"Viola Davis, Denzel Washington, Stephen Hender...",United States,"December 11, 2020",2020,PG-13,91 min,Documentaries,Six ambitious student actors audition for the ...,2434,9
3830,Movie,Ma Rainey's Black Bottom,"Viola Davis, Chadwick Boseman, Glynn Turman, C...",United States,"December 18, 2020",2020,R,94 min,"Dramas, Music & Musicals",Tensions and temperatures rise at a Chicago mu...,3830,9
6670,Movie,The Minimalists: Less Is Now,NaN,United States,"January 1, 2021",2021,TV-14,54 min,Documentaries,They've built a movement out of minimalism. Lo...,6670,1
7569,Movie,What Would Sophia Loren Do?,"Nancy ""Vincenza Careri"" Kulik, Sophia Loren",United States,"January 15, 2021",2021,TV-14,32 min,Documentaries,"In this delightful short documentary, an Itali...",7569,4
1514,Movie,"Crack: Cocaine, Corruption & Conspiracy",NaN,United States,"January 11, 2021",2021,TV-MA,90 min,Documentaries,"A cheap, powerful drug emerges during a recess...",1514,7

# Axis: 

- drop, concat: axis = 0  filas, axis = 1 columnas 

- En funciones aplciado a columnas (mean, std, apply:lambda) DataFrame o matrices Axis = 1 (filas), mientras axos = 0 (columnas)

In [90]:
movie_usa[movie_usa.release_year != 2020]

,type,title,cast,country,date_added,release_year,rating,duration,listed_in,description,new_col,number
6670,Movie,The Minimalists: Less Is Now,NaN,United States,"January 1, 2021",2021,TV-14,54 min,Documentaries,They've built a movement out of minimalism. Lo...,6670,1
7569,Movie,What Would Sophia Loren Do?,"Nancy ""Vincenza Careri"" Kulik, Sophia Loren",United States,"January 15, 2021",2021,TV-14,32 min,Documentaries,"In this delightful short documentary, an Itali...",7569,4
1514,Movie,"Crack: Cocaine, Corruption & Conspiracy",NaN,United States,"January 11, 2021",2021,TV-MA,90 min,Documentaries,"A cheap, powerful drug emerges during a recess...",1514,7

In [91]:
#Rename variables

movie_usa.rename(columns = {'title':'Titulo_movie', 'duration':'Duration_movie'}, inplace = True)

C:\Users\Roberto\AppData\Local\Temp\ipykernel_27528\1458485735.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movie_usa.rename(columns = {'title':'Titulo_movie', 'duration':'Duration_movie'}, inplace = True)

In [92]:
movie_usa

,type,Titulo_movie,cast,country,date_added,release_year,rating,Duration_movie,listed_in,description,new_col,number
154,Movie,A California Christmas,"Lauren Swickard, Josh Swickard, Ali Afshar, Da...",United States,"December 14, 2020",2020,PG-13,107 min,"Comedies, Romantic Movies","With his carefree lifestyle on the line, a wea...",154,1
611,Movie,Athlete A,NaN,United States,"June 24, 2020",2020,PG-13,104 min,"Documentaries, Sports Movies",This documentary focuses on the gymnasts who s...,611,1
1135,Movie,Bulletproof 2,"Faizon Love, Kirk Fox, Tony Todd, Pearl Thusi,...",United States,"January 9, 2020",2020,TV-MA,97 min,"Action & Adventure, Comedies",A special agent abruptly reunites with a crimi...,1135,1
1569,Movie,Da 5 Bloods,"Delroy Lindo, Jonathan Majors, Clarke Peters, ...",United States,"June 12, 2020",2020,R,156 min,"Action & Adventure, Dramas",Four African American veterans return to Vietn...,1569,1
7370,Movie,Uppity: The Willy T. Ribbs Story,Willy T. Ribbs,United States,"February 5, 2020",2020,TV-MA,106 min,"Documentaries, Sports Movies",This documentary profiles a defiant driver who...,7370,1
...,...,...,...,...,...,...,...,...,...,...,...,...
2434,Movie,Giving Voice,"Viola Davis, Denzel Washington, Stephen Hender...",United States,"December 11, 2020",2020,PG-13,91 min,Documentaries,Six ambitious student actors audition for the ...,2434,9
3830,Movie,Ma Rainey's Black Bottom,"Viola Davis, Chadwick Boseman, Glynn Turman, C...",United States,"December 18, 2020",2020,R,94 min,"Dramas, Music & Musicals",Tensions and temperatures rise at a Chicago mu...,3830,9
6670,Movie,The Minimalists: Less Is Now,NaN,United States,"January 1, 2021",2021,TV-14,54 min,Documentaries,They've built a movement out of minimalism. Lo...,6670,1
7569,Movie,What Would Sophia Loren Do?,"Nancy ""Vincenza Careri"" Kulik, Sophia Loren",United States,"January 15, 2021",2021,TV-14,32 min,Documentaries,"In this delightful short documentary, an Itali...",7569,4
1514,Movie,"Crack: Cocaine, Corruption & Conspiracy",NaN,United States,"January 11, 2021",2021,TV-MA,90 min,Documentaries,"A cheap, powerful drug emerges during a recess...",1514,7

### Export data

In [93]:
movie_usa.to_csv("../data/movie_usa_1.csv")

In [94]:
movie_usa.to_excel("../data/movie_usa_1.xlsx")

### References 

https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.dropna.html